/**
 * TwelveLittleScoutsClerk View subdialog for a Bill
 * @author Copyright (c) 2023-2026 Martin Oberzalek
 */
package at.redeye.twelvelittlescoutsclerk.dialog_bill;

import at.redeye.FrameWork.base.AutoMBox;
import at.redeye.FrameWork.base.BaseDialogDialog;
import at.redeye.twelvelittlescoutsclerk.MainWin;
import at.redeye.twelvelittlescoutsclerk.bindtypes.DBBill;
import java.io.File;
import java.io.FileOutputStream;
import javax.swing.JFileChooser;

// generated by AI (Claude Sonnet 4.6)
public class ViewBill extends BaseDialogDialog {

    DBBill entity;
    MainWin mainwin;

    public ViewBill(MainWin mainwin, DBBill entity) {
        super(mainwin.getRoot(), "Rechnung anzeigen");
        initComponents();

        this.entity = entity;
        this.mainwin = mainwin;

        jLBillingnr.setText(entity.billingnr.toString());
        jLFileName.setText(entity.file_name.toString().isEmpty() ? "(keine Datei)" : entity.file_name.toString());
        jLState.setText(entity.state.handler.getValueAsString());
        jLDirection.setText(entity.direction.handler.getValueAsString());

        jBDownloadODT.setEnabled(entity.odt_data.value != null && entity.odt_data.value.length > 0);
        jBDownloadPDF.setEnabled(entity.pdf_data.value != null && entity.pdf_data.value.length > 0);
    }

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelBillingnr = new javax.swing.JLabel();
        jLBillingnr = new javax.swing.JLabel();
        jLabelFileName = new javax.swing.JLabel();
        jLFileName = new javax.swing.JLabel();
        jLabelState = new javax.swing.JLabel();
        jLState = new javax.swing.JLabel();
        jLabelDirection = new javax.swing.JLabel();
        jLDirection = new javax.swing.JLabel();
        jPanelButtons = new javax.swing.JPanel();
        jBDownloadODT = new javax.swing.JButton();
        jBDownloadPDF = new javax.swing.JButton();
        jPanelActions = new javax.swing.JPanel();
        jBClose = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(480, 280));

        jLabelBillingnr.setText("Rechnungsnummer:");
        jLBillingnr.setText(" ");

        jLabelFileName.setText("Dateiname:");
        jLFileName.setText("(keine Datei)");

        jLabelState.setText("Status:");
        jLState.setText(" ");

        jLabelDirection.setText("Richtung:");
        jLDirection.setText(" ");

        jBDownloadODT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/at/redeye/FrameWork/base/resources/icons/fileclose.gif"))); // NOI18N
        jBDownloadODT.setText("ODT herunterladen");
        jBDownloadODT.setEnabled(false);
        jBDownloadODT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBDownloadODTActionPerformed(evt);
            }
        });

        jBDownloadPDF.setIcon(new javax.swing.ImageIcon(getClass().getResource("/at/redeye/FrameWork/base/resources/icons/fileclose.gif"))); // NOI18N
        jBDownloadPDF.setText("PDF herunterladen");
        jBDownloadPDF.setEnabled(false);
        jBDownloadPDF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBDownloadPDFActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelButtonsLayout = new javax.swing.GroupLayout(jPanelButtons);
        jPanelButtons.setLayout(jPanelButtonsLayout);
        jPanelButtonsLayout.setHorizontalGroup(
            jPanelButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelButtonsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jBDownloadODT)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBDownloadPDF)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelButtonsLayout.setVerticalGroup(
            jPanelButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelButtonsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBDownloadODT)
                    .addComponent(jBDownloadPDF))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jBClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/at/redeye/FrameWork/base/resources/icons/fileclose.gif"))); // NOI18N
        jBClose.setText("Schließen");
        jBClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCloseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelActionsLayout = new javax.swing.GroupLayout(jPanelActions);
        jPanelActions.setLayout(jPanelActionsLayout);
        jPanelActionsLayout.setHorizontalGroup(
            jPanelActionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelActionsLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jBClose)
                .addContainerGap())
        );
        jPanelActionsLayout.setVerticalGroup(
            jPanelActionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelActionsLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jBClose)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelButtons, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanelActions, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelBillingnr)
                    .addComponent(jLabelFileName)
                    .addComponent(jLabelState)
                    .addComponent(jLabelDirection))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLBillingnr, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLFileName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLState, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLDirection, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelBillingnr)
                    .addComponent(jLBillingnr))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelFileName)
                    .addComponent(jLFileName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelState)
                    .addComponent(jLState))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelDirection)
                    .addComponent(jLDirection))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanelButtons, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelActions, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCloseActionPerformed
        close();
    }//GEN-LAST:event_jBCloseActionPerformed

    private void jBDownloadODTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBDownloadODTActionPerformed
        downloadFile(entity.odt_data.value, entity.file_name.toString().isEmpty() ? "rechnung.odt" : entity.file_name.toString());
    }//GEN-LAST:event_jBDownloadODTActionPerformed

    private void jBDownloadPDFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBDownloadPDFActionPerformed
        String name = entity.file_name.toString();
        if (!name.isEmpty()) {
            name = name.replaceFirst("\\.[^.]+$", ".pdf");
        } else {
            name = "rechnung.pdf";
        }
        downloadFile(entity.pdf_data.value, name);
    }//GEN-LAST:event_jBDownloadPDFActionPerformed

    private void downloadFile(byte[] data, String suggestedName) {
        if (data == null || data.length == 0) {
            return;
        }

        JFileChooser chooser = new JFileChooser(mainwin.getLastOpenPath());
        chooser.setDialogTitle("Datei speichern");
        chooser.setSelectedFile(new java.io.File(suggestedName));
        int result = chooser.showSaveDialog(this);
        if (result != JFileChooser.APPROVE_OPTION) {
            return;
        }

        File target = chooser.getSelectedFile();
        mainwin.setLastOpenPath(target.getParent());

        new AutoMBox(ViewBill.class.getName()) {
            @Override
            public void do_stuff() throws Exception {
                try (FileOutputStream fos = new FileOutputStream(target)) {
                    fos.write(data);
                }
            }
        };
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBClose;
    private javax.swing.JButton jBDownloadODT;
    private javax.swing.JButton jBDownloadPDF;
    private javax.swing.JLabel jLBillingnr;
    private javax.swing.JLabel jLDirection;
    private javax.swing.JLabel jLFileName;
    private javax.swing.JLabel jLState;
    private javax.swing.JLabel jLabelBillingnr;
    private javax.swing.JLabel jLabelDirection;
    private javax.swing.JLabel jLabelFileName;
    private javax.swing.JLabel jLabelState;
    private javax.swing.JPanel jPanelActions;
    private javax.swing.JPanel jPanelButtons;
    // End of variables declaration//GEN-END:variables
}
