/**
 * TwelveLittleScoutsClerk Preview dialog for a mail job
 * @author Copyright (c) 2023-2026 Martin Oberzalek
 */
// generated by AI (Claude Sonnet 4.6)
package at.redeye.twelvelittlescoutsclerk.dialog_mailjob;

import at.redeye.FrameWork.base.BaseDialogDialog;
import at.redeye.twelvelittlescoutsclerk.AppConfigDefinitions;
import at.redeye.twelvelittlescoutsclerk.MainWin;
import at.redeye.twelvelittlescoutsclerk.bindtypes.DBMailJob;
import java.io.File;
import java.io.FileOutputStream;
import java.nio.charset.StandardCharsets;
import javax.swing.JOptionPane;

public class MailJobPreview extends BaseDialogDialog {

    private MainWin mainwin;
    private DBMailJob job;

    public MailJobPreview(MailJobs parent, MainWin mainwin, DBMailJob job) {
        super((javax.swing.JFrame) parent, mainwin.getRoot(), "Preview Mail");

        this.mainwin = mainwin;
        this.job = job;

        initComponents();

        jTABody.setFont(new java.awt.Font(java.awt.Font.MONOSPACED, java.awt.Font.PLAIN, 12));
        jLToValue.setText(buildToText(job));
        jLSubjectValue.setText(job.subject.getValue() != null ? job.subject.getValue() : "");
        jTABody.setText(getBody(job));
        jTABody.setCaretPosition(0);
        jBViewPdf.setEnabled(job.pdf_data.value != null && job.pdf_data.value.length > 0);
    }

    private static String buildToText(DBMailJob job) {
        String name = job.recipient_name.getValue();
        String email = job.recipient_email.getValue();
        if (name != null && !name.isBlank() && email != null && !email.isBlank()) {
            return name + " <" + email + ">";
        } else if (email != null && !email.isBlank()) {
            return email;
        }
        return "";
    }

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLToLabel = new javax.swing.JLabel();
        jLToValue = new javax.swing.JLabel();
        jLSubjectLabel = new javax.swing.JLabel();
        jLSubjectValue = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTABody = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        jBViewPdf = new javax.swing.JButton();
        jBClose = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLToLabel.setText("To:");

        jLToValue.setText(" ");

        jLSubjectLabel.setText("Subject:");

        jLSubjectValue.setText(" ");

        jTABody.setEditable(false);
        jTABody.setLineWrap(true);
        jTABody.setWrapStyleWord(true);
        jScrollPane1.setViewportView(jTABody);

        jBViewPdf.setIcon(new javax.swing.ImageIcon(getClass().getResource("/at/redeye/twelvelittlescoutsclerk/resources/icons/pdf_view.png"))); // NOI18N
        jBViewPdf.setText("View PDF");
        jBViewPdf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBViewPdfActionPerformed(evt);
            }
        });

        jBClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/at/redeye/FrameWork/base/resources/icons/fileclose.gif"))); // NOI18N
        jBClose.setText("Close");
        jBClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCloseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLToLabel)
                    .addComponent(jLSubjectLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLToValue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLSubjectValue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLToLabel)
                    .addComponent(jLToValue))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLSubjectLabel)
                    .addComponent(jLSubjectValue))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jBViewPdf)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 100, Short.MAX_VALUE)
                .addComponent(jBClose)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBViewPdf)
                    .addComponent(jBClose))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCloseActionPerformed
        close();
    }//GEN-LAST:event_jBCloseActionPerformed

    private void jBViewPdfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBViewPdfActionPerformed
        try {
            File tmpFile = File.createTempFile("mailjob_", ".pdf");
            tmpFile.deleteOnExit();
            try (FileOutputStream fos = new FileOutputStream(tmpFile)) {
                fos.write(job.pdf_data.value);
            }
            String openCmd = mainwin.getRoot().getSetup().getConfig(AppConfigDefinitions.OpenCommand);
            if (openCmd != null && !openCmd.isBlank()) {
                String resolved = openCmd.contains("%s")
                        ? openCmd.replace("%s", tmpFile.getAbsolutePath())
                        : openCmd + " " + tmpFile.getAbsolutePath();
                new ProcessBuilder(resolved.split("\\s+")).start();
            } else {
                java.awt.Desktop.getDesktop().open(tmpFile);
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), getTitle(), JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jBViewPdfActionPerformed

    private static String getBody(DBMailJob job) {
        if (job.body.value == null || job.body.value.length == 0) {
            return "";
        }
        return new String(job.body.value, StandardCharsets.UTF_8);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBClose;
    private javax.swing.JButton jBViewPdf;
    private javax.swing.JLabel jLSubjectLabel;
    private javax.swing.JLabel jLSubjectValue;
    private javax.swing.JLabel jLToLabel;
    private javax.swing.JLabel jLToValue;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTABody;
    // End of variables declaration//GEN-END:variables
}
