/**
 * TwelveLittleScoutsClerk Dialog for mail dispatch jobs
 * @author Copyright (c) 2023-2026 Martin Oberzalek
 */
// generated by AI (Claude Sonnet 4.6)
package at.redeye.twelvelittlescoutsclerk.dialog_mailjob;

import at.redeye.FrameWork.base.AutoMBox;
import at.redeye.FrameWork.base.BaseDialog;
import at.redeye.FrameWork.base.tablemanipulator.TableManipulator;
import at.redeye.FrameWork.base.transaction.Transaction;
import at.redeye.twelvelittlescoutsclerk.MainWin;
import at.redeye.twelvelittlescoutsclerk.bindtypes.DBMailJob;
import java.util.List;
import javax.swing.JOptionPane;

public class MailJobs extends BaseDialog {

    MainWin mainwin;
    List<DBMailJob> values;
    TableManipulator tm;

    private String MESSAGE_ONLY_FAILED_JOBS;

    public MailJobs(MainWin mainwin) {
        super(mainwin.getRoot(), "Mail Jobs");

        initComponents();
        initMessages();

        this.mainwin = mainwin;

        DBMailJob proto = new DBMailJob();

        tm = new TableManipulator(root, jTContent, proto);

        tm.hide(proto.idx);
        tm.hide(proto.bp_idx);
        tm.hide(proto.bill_idx);
        tm.hide(proto.body);
        tm.hide(proto.pdf_data);
        tm.hide(proto.hist.lo_user);
        tm.hide(proto.hist.lo_zeit);
        tm.hide(proto.hist.ae_user);
        tm.hide(proto.hist.an_user);
        tm.hide(proto.hist.an_zeit);
        tm.hide(proto.hist.ae_zeit);

        tm.prepareTable();

        feed_table(false);

        tm.autoResize();

        tableFilter1.setFilter(jTContent);
    }

    private void initMessages() {
        MESSAGE_ONLY_FAILED_JOBS = MlM("Only failed jobs can be retried.");
    }

    private void feed_table(boolean autombox) {
        new AutoMBox(getTitle(), autombox) {
            @Override
            public void do_stuff() throws Exception {
                tm.clear();
                Transaction trans = getTransaction();
                DBMailJob proto = new DBMailJob();
                values = trans.fetchTable2(proto,
                        "order by " + trans.markColumn(proto.idx) + " desc");
                for (DBMailJob job : values) {
                    tm.add(job);
                }
            }
        };
    }

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTContent = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jBClose = new javax.swing.JButton();
        jBRetry = new javax.swing.JButton();
        jBRefresh = new javax.swing.JButton();
        tableFilter1 = new at.redeye.twelvelittlescoutsclerk.tableFilter();
        jLabel1 = new javax.swing.JLabel();
        jLInfo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

        jTContent.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTContent);

        jBClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/at/redeye/FrameWork/base/resources/icons/fileclose.gif"))); // NOI18N
        jBClose.setText("Close");
        jBClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCloseActionPerformed(evt);
            }
        });

        jBRetry.setIcon(new javax.swing.ImageIcon(getClass().getResource("/at/redeye/FrameWork/base/resources/icons/bookmark.png"))); // NOI18N
        jBRetry.setText("Retry");
        jBRetry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBRetryActionPerformed(evt);
            }
        });

        jBRefresh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/at/redeye/FrameWork/base/resources/icons/reload.png"))); // NOI18N
        jBRefresh.setText("Refresh");
        jBRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBRefreshActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jBRetry)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBRefresh)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addComponent(jBClose)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBRetry)
                    .addComponent(jBRefresh)
                    .addComponent(jBClose))
                .addContainerGap())
        );

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setText("Mail Jobs");

        jLInfo.setText(" ");
        jLInfo.setAutoscrolls(true);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 750, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLInfo, javax.swing.GroupLayout.DEFAULT_SIZE, 356, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tableFilter1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tableFilter1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(jLInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCloseActionPerformed
        close();
    }//GEN-LAST:event_jBCloseActionPerformed

    private void jBRetryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBRetryActionPerformed
        if (!checkAnyAndSingleSelection(jTContent)) {
            return;
        }
        final int row = tm.getSelectedRow();
        if (row < 0 || row >= values.size()) {
            return;
        }
        final DBMailJob job = values.get(row);
        if (job.state.getValue() != DBMailJob.State.FAILED.ordinal()) {
            JOptionPane.showMessageDialog(this,
                    MESSAGE_ONLY_FAILED_JOBS,
                    getTitle(), JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        new AutoMBox(getTitle()) {
            @Override
            public void do_stuff() throws Exception {
                job.state.handler.setValue(DBMailJob.State.PENDING.ordinal());
                job.error_message.loadFromString("");
                getTransaction().updateValues(job);
                getTransaction().commit();
            }
        };
        feed_table(false);
    }//GEN-LAST:event_jBRetryActionPerformed

    private void jBRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBRefreshActionPerformed
        feed_table(false);
    }//GEN-LAST:event_jBRefreshActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBClose;
    private javax.swing.JButton jBRefresh;
    private javax.swing.JButton jBRetry;
    private javax.swing.JLabel jLInfo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTContent;
    private at.redeye.twelvelittlescoutsclerk.tableFilter tableFilter1;
    // End of variables declaration//GEN-END:variables
}
