/**
 * TwelveLittleScoutsClerk bill templates
 * @author Copyright (c) 2023-2026 Martin Oberzalek
 */
package at.redeye.twelvelittlescoutsclerk.bindtypes;

import at.redeye.FrameWork.base.bindtypes.DBBlob;
import at.redeye.FrameWork.base.bindtypes.DBHistory;
import at.redeye.FrameWork.base.bindtypes.DBInteger;
import at.redeye.FrameWork.base.bindtypes.DBString;
import at.redeye.FrameWork.base.bindtypes.DBStrukt;

// generated by AI (Claude Sonnet 4.6)
public class DBBillTemplate extends DBStrukt {

    public static final String BILL_TEMPLATE_IDX_SEQUENCE = "BILL_TEMP_IDX_SEQ";

    public DBInteger idx         = new DBInteger("idx");
    public DBInteger bp_idx      = new DBInteger("bp_idx");
    public DBString  name        = new DBString("name", "Name", 255);
    public DBString  description = new DBString("description", "Beschreibung", 500);
    public DBString  file_name   = new DBString("file_name", "Dateiname", 255);
    public DBBlob    odt_data    = new DBBlob("odt_data");
    public DBHistory hist        = new DBHistory("hist");

    public DBBillTemplate() {
        super("BILL_TEMPLATES");

        add(idx);
        add(bp_idx);
        add(name);
        add(description,2);
        add(file_name,2);
        add(odt_data);
        add(hist);

        idx.setAsPrimaryKey();
        bp_idx.shouldHaveIndex();
        hist.setTitle(" ");

        setVersion(2);
    }

    @Override
    public DBStrukt getNewOne() {
        return new DBBillTemplate();
    }
}
