/**
 * TwelveLittleScoutsClerk bill templates
 * @author Copyright (c) 2023-2026 Martin Oberzalek
 */
package at.redeye.twelvelittlescoutsclerk.bindtypes;

import at.redeye.FrameWork.base.bindtypes.DBBlob;
import at.redeye.FrameWork.base.bindtypes.DBHistory;
import at.redeye.FrameWork.base.bindtypes.DBInteger;
import at.redeye.FrameWork.base.bindtypes.DBString;
import at.redeye.FrameWork.base.bindtypes.DBStrukt;

// generated by AI (Claude Sonnet 4.6)
public class DBBillTemplate extends DBStrukt {

    public static final String BILL_TEMPLATE_IDX_SEQUENCE = "BILL_TEMP_IDX_SEQ";

    // Column references for Condition API
    public static final DBInteger IDX         = new DBInteger("idx");
    public static final DBInteger BP_IDX      = new DBInteger("bp_idx");
    public static final DBString  NAME        = new DBString("name", 1);
    public static final DBString  DESCRIPTION = new DBString("description", 1);
    public static final DBString  FILE_NAME   = new DBString("file_name", 1);
    public static final DBBlob    ODT_DATA    = new DBBlob("odt_data");
    public static final DBHistory HIST        = new DBHistory("hist");

    public DBInteger  idx          = IDX.getCopy();
    public DBInteger  bp_idx       = BP_IDX.getCopy();
    public DBString   name         = NAME.getCopy();
    public DBString   description  = DESCRIPTION.getCopy();
    public DBString   file_name    = FILE_NAME.getCopy();
    public DBBlob     odt_data     = ODT_DATA.getCopy();
    public DBHistory  hist         = (DBHistory)HIST.getCopy();

    public DBBillTemplate() {
        super("BILL_TEMPLATES");

        add(idx);
        add(bp_idx);
        add(name);
        add(description,2);
        add(file_name,2);
        add(odt_data);
        add(hist);

        idx.setAsPrimaryKey();
        bp_idx.shouldHaveIndex();
        hist.setTitle(" ");

        setVersion(2);
    }

    @Override
    public DBStrukt getNewOne() {
        return new DBBillTemplate();
    }
}
