/**
 * TwelveLittleScoutsClerk generated bills
 * @author Copyright (c) 2023-2026 Martin Oberzalek
 */
package at.redeye.twelvelittlescoutsclerk.bindtypes;

import at.redeye.FrameWork.base.bindtypes.DBBlob;
import at.redeye.FrameWork.base.bindtypes.DBEnumAsInteger;
import at.redeye.FrameWork.base.bindtypes.DBHistory;
import at.redeye.FrameWork.base.bindtypes.DBInteger;
import at.redeye.FrameWork.base.bindtypes.DBString;
import at.redeye.FrameWork.base.bindtypes.DBStrukt;
import at.redeye.FrameWork.base.bindtypes.ForeignKeyDefinition;
import java.util.Vector;

// generated by AI (Claude Sonnet 4.6)
public class DBBill extends DBStrukt {

    public static final String BILL_IDX_SEQUENCE = "BILL_IDX_SEQ";
    public static final String REGISTRATION_IDX_SEQUENCE = "REGISTRATION_IDX_SEQ";

    public static final ForeignKeyDefinition FK_BILLING_PERIOD =
        new ForeignKeyDefinition("bp_idx", "BILLING_PERIOD", "idx");

    public enum State { NORMAL, CANCELED }
    public enum Direction { OUTGOING, INCOMING }

    public static class StateHandler extends DBEnumAsInteger.EnumAsIntegerHandler {

        private int value = State.NORMAL.ordinal();

        @Override
        public int getMaxSize() {
            return State.values().length;
        }

        @Override
        public boolean setValue(String val) {
            for (State s : State.values()) {
                if (s.name().equalsIgnoreCase(val)) {
                    value = s.ordinal();
                    return true;
                }
            }
            try {
                int i = Integer.parseInt(val);
                if (i >= 0 && i < State.values().length) {
                    value = i;
                    return true;
                }
            } catch (NumberFormatException ignored) {
            }
            return false;
        }

        @Override
        public boolean setValue(Integer val) {
            if (val >= 0 && val < State.values().length) {
                value = val;
                return true;
            }
            return false;
        }

        @Override
        public Integer getValue() {
            return value;
        }

        @Override
        public String getValueAsString() {
            return State.values()[value].name();
        }

        @Override
        public DBEnumAsInteger.EnumAsIntegerHandler getNewOne() {
            return new StateHandler();
        }

        @Override
        public Vector<String> getPossibleValues() {
            Vector<String> res = new Vector<>();
            for (State s : State.values()) {
                res.add(s.name());
            }
            return res;
        }

        @Override
        public void refresh() {
            // nothing to do
        }
    }

    public static class DirectionHandler extends DBEnumAsInteger.EnumAsIntegerHandler {

        private int value = Direction.OUTGOING.ordinal();

        @Override
        public int getMaxSize() {
            return Direction.values().length;
        }

        @Override
        public boolean setValue(String val) {
            for (Direction d : Direction.values()) {
                if (d.name().equalsIgnoreCase(val)) {
                    value = d.ordinal();
                    return true;
                }
            }
            try {
                int i = Integer.parseInt(val);
                if (i >= 0 && i < Direction.values().length) {
                    value = i;
                    return true;
                }
            } catch (NumberFormatException ignored) {
            }
            return false;
        }

        @Override
        public boolean setValue(Integer val) {
            if (val >= 0 && val < Direction.values().length) {
                value = val;
                return true;
            }
            return false;
        }

        @Override
        public Integer getValue() {
            return value;
        }

        @Override
        public String getValueAsString() {
            return Direction.values()[value].name();
        }

        @Override
        public DBEnumAsInteger.EnumAsIntegerHandler getNewOne() {
            return new DirectionHandler();
        }

        @Override
        public Vector<String> getPossibleValues() {
            Vector<String> res = new Vector<>();
            for (Direction d : Direction.values()) {
                res.add(d.name());
            }
            return res;
        }

        @Override
        public void refresh() {
            // nothing to do
        }
    }

    public enum BillType { INVOICE, REGISTRATION }

    public static class BillTypeHandler extends DBEnumAsInteger.EnumAsIntegerHandler {

        private int value = BillType.INVOICE.ordinal();

        @Override
        public int getMaxSize() {
            return BillType.values().length;
        }

        @Override
        public boolean setValue(String val) {
            for (BillType t : BillType.values()) {
                if (t.name().equalsIgnoreCase(val)) {
                    value = t.ordinal();
                    return true;
                }
            }
            try {
                int i = Integer.parseInt(val);
                if (i >= 0 && i < BillType.values().length) {
                    value = i;
                    return true;
                }
            } catch (NumberFormatException ignored) {
            }
            return false;
        }

        @Override
        public boolean setValue(Integer val) {
            if (val >= 0 && val < BillType.values().length) {
                value = val;
                return true;
            }
            return false;
        }

        @Override
        public Integer getValue() {
            return value;
        }

        @Override
        public String getValueAsString() {
            return BillType.values()[value].name();
        }

        @Override
        public DBEnumAsInteger.EnumAsIntegerHandler getNewOne() {
            return new BillTypeHandler();
        }

        @Override
        public Vector<String> getPossibleValues() {
            Vector<String> res = new Vector<>();
            for (BillType t : BillType.values()) {
                res.add(t.name());
            }
            return res;
        }

        @Override
        public void refresh() {
            // nothing to do
        }
    }

    public static final DBInteger       IDX                  = new DBInteger("idx");
    public static final DBInteger       BP_IDX               = new DBInteger("bp_idx");
    public static final DBString        BILLINGNR            = new DBString("billingnr", "Billing Nr", 50);
    public static final DBString        FILE_NAME            = new DBString("file_name", "File Name", 255);
    public static final DBBlob          ODT_DATA             = new DBBlob("odt_data");
    public static final DBBlob          PDF_DATA             = new DBBlob("pdf_data");
    public static final DBEnumAsInteger STATE                = new DBEnumAsInteger("state", "State", new StateHandler());
    public static final DBString        CANCEL_REASON        = new DBString("cancel_reason", "Cancel Reason", 255);
    public static final DBEnumAsInteger DIRECTION            = new DBEnumAsInteger("direction", "Direction", new DirectionHandler());
    public static final DBEnumAsInteger BILL_TYPE            = new DBEnumAsInteger("bill_type", "Bill Type", new BillTypeHandler());
    public static final DBInteger       REGISTRATION_NUMBER  = new DBInteger("registration_number");  // seq from REGISTRATION_IDX_SEQ
    public static final DBHistory       HIST                 = new DBHistory("hist");
    

    public DBInteger       idx                  = IDX.getCopy();
    public DBInteger       bp_idx               = BP_IDX.getCopy();
    public DBString        billingnr            = BILLINGNR.getCopy();
    public DBString        file_name            = FILE_NAME.getCopy();
    public DBBlob          odt_data             = ODT_DATA.getCopy();
    public DBBlob          pdf_data             = PDF_DATA.getCopy();
    public DBEnumAsInteger state                = (DBEnumAsInteger) STATE.getCopy();
    public DBString        cancel_reason        = CANCEL_REASON.getCopy();
    public DBEnumAsInteger direction            = (DBEnumAsInteger) DIRECTION.getCopy();
    public DBEnumAsInteger bill_type            = (DBEnumAsInteger) BILL_TYPE.getCopy();
    public DBInteger       registration_number  = REGISTRATION_NUMBER.getCopy();
    public DBHistory       hist                 = (DBHistory) HIST.getCopy();    

    public DBBill() {
        super("BILLS");

        add(idx);
        add(bp_idx);
        add(billingnr);
        add(file_name);
        add(odt_data);
        add(pdf_data);
        add(state);
        add(cancel_reason, 6);
        add(direction, 2);
        add(bill_type, 3);
        add(registration_number, 4);
        add(hist);        

        idx.setAsPrimaryKey();
        bp_idx.shouldHaveIndex();
        hist.setTitle(" ");

        addForeignKey(FK_BILLING_PERIOD, 5);

        setVersion(6);
    }

    @Override
    public DBStrukt getNewOne() {
        return new DBBill();
    }

    public boolean isCanceled() {
        return State.CANCELED.ordinal() == state.getValue();
    }

    public boolean isRegistration() {
        return BillType.REGISTRATION.ordinal() == bill_type.getValue();
    }
}
