/**
 * TwelveLittleScoutsClerk Cash Flow report renderer
 * @author Copyright (c) 2026 Martin Oberzalek
 */
// generated by AI (GitHub Copilot / Claude Sonnet 4.6)
package at.redeye.twelvelittlescoutsclerk.reports.cashflow;

import at.redeye.FrameWork.base.AutoLogger;
import at.redeye.FrameWork.base.bindtypes.DBDateTime;
import at.redeye.FrameWork.base.reports.BaseReportRenderer;
import at.redeye.FrameWork.base.reports.ReportRenderer;
import at.redeye.FrameWork.base.transaction.Transaction;
import at.redeye.twelvelittlescoutsclerk.DateFilter;
import at.redeye.twelvelittlescoutsclerk.bindtypes.DBAccountClasses;
import at.redeye.twelvelittlescoutsclerk.bindtypes.DBBillingPeriod;
import at.redeye.twelvelittlescoutsclerk.bindtypes.DBBookingLine;
import at.redeye.twelvelittlescoutsclerk.bindtypes.DBBookingLine2Events;
import at.redeye.twelvelittlescoutsclerk.bindtypes.DBEvent;
import at.redeye.twelvelittlescoutsclerk.dialog_bookingline.BookingLine;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.HashSet;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.Vector;
import org.apache.log4j.Logger;

// AI-generated start (GitHub Copilot / Claude Sonnet 4.6)
public class ReportCashFlowRenderer extends BaseReportRenderer implements ReportRenderer {

    private static final Logger logger = Logger.getLogger(ReportCashFlowRenderer.class.getName());

    private final Transaction trans;
    private final DBBillingPeriod bp;
    private final double currentBankCash;
    private final DBDateTime dateFrom;
    private final DBDateTime dateTill;
    private final Set<DBAccountClasses.Category> categoryFilter;
    
    // Data structures for export
    private LinkedHashMap<Integer, String> acNames;
    private LinkedHashMap<Integer, Double> sumByClass;
    private List<DBBookingLine> bookingLines;
    private double grandTotal;
    private double plannedCostsTotal;
    private double paidTotal;

    public ReportCashFlowRenderer(Transaction trans, DBBillingPeriod bp, double currentBankCash,
            DBDateTime dateFrom, DBDateTime dateTill, Set<DBAccountClasses.Category> categoryFilter) {
        this.trans = trans;
        this.bp = bp;
        this.currentBankCash = currentBankCash;
        this.dateFrom = dateFrom != null ? dateFrom : new DBDateTime("dummy");
        this.dateTill = dateTill != null ? dateTill : new DBDateTime("dummy");
        this.categoryFilter = categoryFilter != null ? categoryFilter : Set.of(DBAccountClasses.Category.values());
        this.acNames = new LinkedHashMap<>();
        this.sumByClass = new LinkedHashMap<>();
        this.bookingLines = new ArrayList<>();
    }

    @Override
    public boolean collectData() {
        return true; // data is fetched inline in render()
    }

    @Override
    public String render() {
        AutoLogger al = new AutoLogger(ReportCashFlowRenderer.class.getSimpleName()) {
            @Override
            public void do_stuff() throws Exception {
                result = doRender();
            }
        };
        if (al.result instanceof String) {
            return (String) al.result;
        }
        return "<html><body>Error generating report</body></html>";
    }

    private String doRender() throws Exception {
        // --- load all events for this billing period into a map ---
        DBEvent evProto = new DBEvent();
        List<DBEvent> events = trans.fetchTable2(evProto,
                "where " + trans.markColumn(evProto, evProto.bp_idx) + " = " + bp.idx);
        Map<Integer, DBEvent> eventMap = new HashMap<>();
        for (DBEvent ev : events) {
            eventMap.put(ev.idx.getValue(), ev);
        }

        // --- load booking-line → event assignments ---
        DBBookingLine2Events b2eProto = new DBBookingLine2Events();
        List<DBBookingLine2Events> b2es = trans.fetchTable2(b2eProto,
                "where " + trans.markColumn(b2eProto, b2eProto.bp_idx) + " = " + bp.idx);
        Map<Integer, Integer> blToEvent = new HashMap<>(); // bl_idx -> event_idx
        for (DBBookingLine2Events b2e : b2es) {
            blToEvent.put(b2e.bl_idx.getValue(), b2e.event_idx.getValue());
        }

        // --- load account classes for this billing period ---
        DBAccountClasses acProto = new DBAccountClasses();
        List<DBAccountClasses> accountClasses = trans.fetchTable2(acProto,
                "where " + trans.markColumn(acProto, acProto.bp_idx) + " = " + bp.idx
                + " order by " + trans.markColumn(acProto, acProto.name));

        // build a set of account class indices that match the selected category filter
        Set<Integer> filteredAcIdx = new HashSet<>();
        this.acNames.clear();
        this.acNames.put(0, "(unassigned)");
        // (unassigned) always passes the filter
        filteredAcIdx.add(0);
        for (DBAccountClasses ac : accountClasses) {
            this.acNames.put(ac.idx.getValue(), ac.name.toString());
            DBAccountClasses.Category cat = DBAccountClasses.Category.values()[ac.category.getValue()];
            if (categoryFilter.contains(cat)) {
                filteredAcIdx.add(ac.idx.getValue());
            }
        }

        // --- load all booking lines for this billing period (no splits) ---
        DBBookingLine blProto = new DBBookingLine();
        String dateFilter = DateFilter.getVonBisFilter(trans, dateFrom, dateTill, blProto.date);
        List<DBBookingLine> lines = trans.fetchTable2(blProto,
                "where " + trans.markColumn(blProto, blProto.bp_idx) + " = " + bp.idx
                + " and " + trans.markColumn(blProto, blProto.splitpos) + " = 0"
                + dateFilter
                + " order by " + trans.markColumn(blProto, blProto.date));
        this.bookingLines = lines;

        // --- accumulate sums per account class idx ---
        // Rule:
        //   - line has no event assignment → always count
        //   - line has event assignment → count only if event.counts_to_available_cash_amount == true
        //   - also skip lines whose account class category is not in the filter
        this.sumByClass.clear();
        for (Integer k : this.acNames.keySet()) {
            this.sumByClass.put(k, 0.0);
        }

        this.grandTotal = 0.0;
        this.plannedCostsTotal = 0.0;
        this.paidTotal = 0.0;

        for (DBBookingLine bl : lines) {
            Integer eventIdx = blToEvent.get(bl.idx.getValue());
            if (eventIdx != null) {
                DBEvent ev = eventMap.get(eventIdx);
                if (ev == null || ev.counts_to_available_cash_amount.getValue() == 0) {
                    continue; // skip: assigned to event that does NOT count toward cash
                }
            }

            int acIdx = bl.account_class_idx.getValue();
            double amount = bl.amount.getValue();

            // skip account classes not in the category filter
            if (!filteredAcIdx.contains(acIdx)) {
                continue;
            }

            logger.info( "blIdx: " + bl.idx.getValue() + ", ac: " + bl.account_class.toString() + ", amount: " + amount ); 

            this.sumByClass.merge(acIdx, amount, Double::sum);
            this.grandTotal += amount;
        }

        // --- calculate planned costs and costs for events with counts_to_available_cash_amount ---
        for (DBEvent ev : events) {
            if (ev.counts_to_available_cash_amount.getValue() == 1) {
                double evPlanned = ev.planned_costs.getValue();
                double evPaid = ev.paid.getValue();
                this.plannedCostsTotal += evPlanned;
                this.paidTotal += evPaid;
                logger.info("Event '" + ev.name.getValue() + "' counts to available cash: planned_costs=" + evPlanned + ", costs=" + evPaid);
            }
        }
        logger.info("Total planned costs for counting events: " + plannedCostsTotal);
        logger.info("Total costs for counting events: " + paidTotal);

        // --- render HTML ---
        clear();
        html_start();
        html_setTitle("Cash Flow — " + bp.title);

        // starting balance
        text.append("<p><b>Current bank account cash: </b>")
            .append(String.format("%.2f", currentBankCash))
            .append("</p>");

        // date range info
        if (dateFrom != null && dateFrom.getValue() != null && dateFrom.getValue().getTime() > 0
                && dateTill != null && dateTill.getValue() != null && dateTill.getValue().getTime() > 0) {
            text.append("<p><b>Date range: </b>")
                .append(dateFrom.toString())
                .append(" to ")
                .append(dateTill.toString())
                .append("</p>");
        }

        html_newline();

        // table header
        text.append("<table border='1' cellpadding='4' cellspacing='0' style='border-collapse:collapse;'>");
        text.append("<tr><th align='left'>Account Class</th><th align='right'>Sum (€)</th></tr>");

        for (Map.Entry<Integer, String> entry : this.acNames.entrySet()) {
            int acIdx = entry.getKey();
            double sum = this.sumByClass.getOrDefault(acIdx, 0.0);
            if (sum == 0.0) {
                continue; // skip empty classes for brevity
            }
            text.append("<tr><td>").append(escapeHtml(entry.getValue())).append("</td>")
                .append("<td align='right'>").append(String.format("%.2f", sum)).append("</td></tr>");
        }

        text.append("<tr style='font-weight:bold'><td>Total from booking lines</td>")
            .append("<td align='right'>").append(String.format("%.2f", this.grandTotal)).append("</td></tr>");

        double available = currentBankCash + this.grandTotal;
        text.append("<tr style='font-weight:bold;background-color:#d0f0d0'><td>Available cash (bank + total)</td>")
            .append("<td align='right'>").append(String.format("%.2f", available)).append("</td></tr>");

        // --- add planned costs information for events with counts_to_available_cash_amount ---
        double plannedCostsMinusCosts = this.plannedCostsTotal - this.paidTotal;
        if (plannedCostsTotal > 0 || paidTotal > 0) {
            text.append("<tr><td>Planned costs - Costs (for counting events)</td>");
            text.append("<td align='right'>").append(String.format("%.2f", plannedCostsMinusCosts)).append("</td></tr>");
            
            double estimatedIncome = available + plannedCostsMinusCosts;
            text.append("<tr style='font-weight:bold;background-color:#f0f0d0'><td>Estimated income (available + planned - costs)</td>");
            text.append("<td align='right'>").append(String.format("%.2f", estimatedIncome)).append("</td></tr>");
        }

        text.append("</table>");
        html_stop();

        return text.toString();
    }

    private static String escapeHtml(String s) {
        if (s == null) return "";
        return s.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;");
    }
    
    // Getters for data export
    public LinkedHashMap<Integer, String> getAccountClassNames() {
        return new LinkedHashMap<>(this.acNames);
    }
    
    public LinkedHashMap<Integer, Double> getSumByClass() {
        return new LinkedHashMap<>(this.sumByClass);
    }
    
    public double getGrandTotal() {
        return this.grandTotal;
    }
    
    public double getPlannedCostsTotal() {
        return this.plannedCostsTotal;
    }
    
    public double getPaidTotal() {
        return this.paidTotal;
    }
    
    public double getCurrentBankCash() {
        return this.currentBankCash;
    }
    
    public List<DBBookingLine> getBookingLines() {
        return new ArrayList<>(this.bookingLines);
    }
    
    public DBBillingPeriod getBillingPeriod() {
        return this.bp;
    }
}
// AI-generated end
