/**
 * TwelveLittleScoutsClerk Cash Flow report renderer
 * @author Copyright (c) 2026 Martin Oberzalek
 */
// generated by AI (GitHub Copilot / Claude Sonnet 4.6)
package at.redeye.twelvelittlescoutsclerk.reports.cashflow;

import at.redeye.FrameWork.base.AutoLogger;
import at.redeye.FrameWork.base.reports.BaseReportRenderer;
import at.redeye.FrameWork.base.reports.ReportRenderer;
import at.redeye.FrameWork.base.transaction.Transaction;
import at.redeye.twelvelittlescoutsclerk.bindtypes.DBAccountClasses;
import at.redeye.twelvelittlescoutsclerk.bindtypes.DBBillingPeriod;
import at.redeye.twelvelittlescoutsclerk.bindtypes.DBBookingLine;
import at.redeye.twelvelittlescoutsclerk.bindtypes.DBBookingLine2Events;
import at.redeye.twelvelittlescoutsclerk.bindtypes.DBEvent;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

// AI-generated start (GitHub Copilot / Claude Sonnet 4.6)
public class ReportCashFlowRenderer extends BaseReportRenderer implements ReportRenderer {

    private final Transaction trans;
    private final DBBillingPeriod bp;
    private final double currentBankCash;

    public ReportCashFlowRenderer(Transaction trans, DBBillingPeriod bp, double currentBankCash) {
        this.trans = trans;
        this.bp = bp;
        this.currentBankCash = currentBankCash;
    }

    @Override
    public boolean collectData() {
        return true; // data is fetched inline in render()
    }

    @Override
    public String render() {
        AutoLogger al = new AutoLogger(ReportCashFlowRenderer.class.getSimpleName()) {
            @Override
            public void do_stuff() throws Exception {
                result = doRender();
            }
        };
        if (al.result instanceof String) {
            return (String) al.result;
        }
        return "<html><body>Error generating report</body></html>";
    }

    private String doRender() throws Exception {
        // --- load all events for this billing period into a map ---
        DBEvent evProto = new DBEvent();
        List<DBEvent> events = trans.fetchTable2(evProto,
                "where " + trans.markColumn(evProto, evProto.bp_idx) + " = " + bp.idx);
        Map<Integer, DBEvent> eventMap = new HashMap<>();
        for (DBEvent ev : events) {
            eventMap.put(ev.idx.getValue(), ev);
        }

        // --- load booking-line → event assignments ---
        DBBookingLine2Events b2eProto = new DBBookingLine2Events();
        List<DBBookingLine2Events> b2es = trans.fetchTable2(b2eProto,
                "where " + trans.markColumn(b2eProto, b2eProto.bp_idx) + " = " + bp.idx);
        Map<Integer, Integer> blToEvent = new HashMap<>(); // bl_idx -> event_idx
        for (DBBookingLine2Events b2e : b2es) {
            blToEvent.put(b2e.bl_idx.getValue(), b2e.event_idx.getValue());
        }

        // --- load account classes for this billing period ---
        DBAccountClasses acProto = new DBAccountClasses();
        List<DBAccountClasses> accountClasses = trans.fetchTable2(acProto,
                "where " + trans.markColumn(acProto, acProto.bp_idx) + " = " + bp.idx
                + " order by " + trans.markColumn(acProto, acProto.name));
        Map<Integer, String> acNames = new LinkedHashMap<>();
        acNames.put(0, "(unassigned)");
        for (DBAccountClasses ac : accountClasses) {
            acNames.put(ac.idx.getValue(), ac.name.toString());
        }

        // --- load all booking lines for this billing period (no splits) ---
        DBBookingLine blProto = new DBBookingLine();
        List<DBBookingLine> lines = trans.fetchTable2(blProto,
                "where " + trans.markColumn(blProto, blProto.bp_idx) + " = " + bp.idx
                + " and " + trans.markColumn(blProto, blProto.splitpos) + " = 0"
                + " order by " + trans.markColumn(blProto, blProto.date));

        // --- accumulate sums per account class idx ---
        // Rule:
        //   - line has no event assignment → always count
        //   - line has event assignment → count only if event.counts_to_available_cash_amount == true
        Map<Integer, Double> sumByClass = new LinkedHashMap<>();
        for (Integer k : acNames.keySet()) {
            sumByClass.put(k, 0.0);
        }

        double grandTotal = 0.0;

        for (DBBookingLine bl : lines) {
            Integer eventIdx = blToEvent.get(bl.idx.getValue());
            if (eventIdx != null) {
                DBEvent ev = eventMap.get(eventIdx);
                if (ev == null || ev.counts_to_available_cash_amount.getValue() == 0) {
                    continue; // skip: assigned to event that does NOT count toward cash
                }
            }

            int acIdx = bl.account_class_idx.getValue();
            double amount = bl.amount.getValue();

            sumByClass.merge(acIdx, amount, Double::sum);
            grandTotal += amount;
        }

        // --- render HTML ---
        clear();
        html_start();
        html_setTitle("Cash Flow — " + bp.title);

        // starting balance
        text.append("<p><b>Current bank account cash: </b>")
            .append(String.format("%.2f", currentBankCash))
            .append("</p>");

        html_newline();

        // table header
        text.append("<table border='1' cellpadding='4' cellspacing='0' style='border-collapse:collapse;'>");
        text.append("<tr><th align='left'>Account Class</th><th align='right'>Sum (€)</th></tr>");

        for (Map.Entry<Integer, String> entry : acNames.entrySet()) {
            int acIdx = entry.getKey();
            double sum = sumByClass.getOrDefault(acIdx, 0.0);
            if (sum == 0.0) {
                continue; // skip empty classes for brevity
            }
            text.append("<tr><td>").append(escapeHtml(entry.getValue())).append("</td>")
                .append("<td align='right'>").append(String.format("%.2f", sum)).append("</td></tr>");
        }

        text.append("<tr style='font-weight:bold'><td>Total from booking lines</td>")
            .append("<td align='right'>").append(String.format("%.2f", grandTotal)).append("</td></tr>");

        double available = currentBankCash + grandTotal;
        text.append("<tr style='font-weight:bold;background-color:#d0f0d0'><td>Available cash (bank + total)</td>")
            .append("<td align='right'>").append(String.format("%.2f", available)).append("</td></tr>");

        text.append("</table>");
        html_stop();

        return text.toString();
    }

    private static String escapeHtml(String s) {
        if (s == null) return "";
        return s.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;");
    }
}
// AI-generated end
