/**
 * TwelveLittleScoutsClerk Cash Flow report dialog
 * @author Copyright (c) 2026 Martin Oberzalek
 */
// generated by AI (GitHub Copilot / Claude Sonnet 4.6)
package at.redeye.twelvelittlescoutsclerk.reports.cashflow;

import at.redeye.FrameWork.base.AutoMBox;
import at.redeye.FrameWork.base.BaseDialog;
import at.redeye.FrameWork.base.bindtypes.DBDateTime;
import at.redeye.Plugins.JDatePicker.JDatePicker;
import at.redeye.twelvelittlescoutsclerk.MainWin;
import at.redeye.twelvelittlescoutsclerk.reports.FixNimbusBackgroundColor;
import java.io.File;
import java.io.FileOutputStream;
import javax.swing.JFileChooser;

// AI-generated start (GitHub Copilot / Claude Sonnet 4.6)
public class ReportCashFlow extends BaseDialog {

    private static final String CONFIG_BANK_CASH = ReportCashFlow.class.getName() + ".bankCash";
    private static final String CONFIG_DATE_FROM = ReportCashFlow.class.getName() + ".dateFrom";
    private static final String CONFIG_DATE_TILL = ReportCashFlow.class.getName() + ".dateTill";

    private final MainWin mainwin;
    private final DBDateTime dateFrom;
    private final DBDateTime dateTill;

    public ReportCashFlow(MainWin mainwin) {
        super(mainwin.getRoot(), "Cash Flow");
        this.mainwin = mainwin;
        dateFrom = new DBDateTime("dateFrom");
        dateTill = new DBDateTime("dateTill");
        initComponents();

        FixNimbusBackgroundColor.fixNimbusBackgroundColor(jReport);

        // restore last-used bank cash value
        String saved = root.getSetup().getLocalConfig(CONFIG_BANK_CASH, "0.0");
        jTBankCash.setText(saved);

        // restore last-used date range
        String savedFrom = root.getSetup().getLocalConfig(CONFIG_DATE_FROM, "");
        String savedTill = root.getSetup().getLocalConfig(CONFIG_DATE_TILL, "");
        try {
            if (!savedFrom.trim().isEmpty()) {
                dateFrom.loadFromString(savedFrom);
            }
        } catch (Exception ex) {
            logger.error(ex, ex);
        }
        try {
            if (!savedTill.trim().isEmpty()) {
                dateTill.loadFromString(savedTill);
            }
        } catch (Exception ex) {
            logger.error(ex, ex);
        }

        // bind date fields to UI components
        bindVar(jDateFrom, dateFrom);
        bindVar(jDateTill, dateTill);
        
        // make date pickers text-editable like in Operational dialog
        jDateFrom.setTextEditable(true);
        jDateTill.setTextEditable(true);
        
        var_to_gui();
    }

    @Override
    public void close() {
        gui_to_var();
        root.getSetup().setLocalConfig(CONFIG_BANK_CASH, jTBankCash.getText().trim());
        root.getSetup().setLocalConfig(CONFIG_DATE_FROM, dateFrom.toString());
        root.getSetup().setLocalConfig(CONFIG_DATE_TILL, dateTill.toString());
        super.close();
    }

    private double parseBankCash() {
        try {
            return Double.parseDouble(jTBankCash.getText().trim().replace(",", "."));
        } catch (NumberFormatException e) {
            return 0.0;
        }
    }

    private void generateReport() {
        new AutoMBox(getTitle()) {
            @Override
            public void do_stuff() throws Exception {
                setWaitCursor();
                gui_to_var();
                double bankCash = parseBankCash();
                ReportCashFlowRenderer renderer =
                        new ReportCashFlowRenderer(getTransaction(), mainwin.getAZ(), bankCash, dateFrom, dateTill);
                renderer.collectData();
                jReport.setText(renderer.render());
                jReport.setCaretPosition(0);
                setWaitCursor(false);
            }
        };
    }

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanelCashFlow = new javax.swing.JPanel();
        jPanelControls = new javax.swing.JPanel();
        jLabelBankCash = new javax.swing.JLabel();
        jTBankCash = new javax.swing.JTextField();
        jLabelDateFrom = new javax.swing.JLabel();
        jDateFrom = new JDatePicker(root);
        jLabelDateTill = new javax.swing.JLabel();
        jDateTill = new JDatePicker(root);
        jBGenerate = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jReport = new javax.swing.JTextPane();
        jPanelButtons = new javax.swing.JPanel();
        jBExportODT = new javax.swing.JButton();
        jBPrint = new javax.swing.JButton();
        jBClose = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

        // --- controls panel ---
        jLabelBankCash.setText("Current bank account cash (€):");

        jTBankCash.setColumns(12);

        jLabelDateFrom.setText("From:");

        jLabelDateTill.setText("Till:");

        jBGenerate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/at/redeye/FrameWork/base/resources/icons/reload.png"))); // NOI18N
        jBGenerate.setText("Generate Cash Flow");
        jBGenerate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBGenerateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelControlsLayout = new javax.swing.GroupLayout(jPanelControls);
        jPanelControls.setLayout(jPanelControlsLayout);
        jPanelControlsLayout.setHorizontalGroup(
            jPanelControlsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelControlsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelControlsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelControlsLayout.createSequentialGroup()
                        .addComponent(jLabelBankCash)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTBankCash, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelControlsLayout.createSequentialGroup()
                        .addComponent(jLabelDateFrom)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jDateFrom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelDateTill)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jDateTill, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jBGenerate)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelControlsLayout.setVerticalGroup(
            jPanelControlsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelControlsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelControlsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelBankCash)
                    .addComponent(jTBankCash, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBGenerate))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelControlsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelDateFrom)
                    .addComponent(jDateFrom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelDateTill)
                    .addComponent(jDateTill, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        // --- report area ---
        jReport.setContentType("text/html");
        jReport.setEditable(false);
        jScrollPane1.setViewportView(jReport);

        // --- cash flow tab layout ---
        javax.swing.GroupLayout jPanelCashFlowLayout = new javax.swing.GroupLayout(jPanelCashFlow);
        jPanelCashFlow.setLayout(jPanelCashFlowLayout);
        jPanelCashFlowLayout.setHorizontalGroup(
            jPanelCashFlowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelControls, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1)
        );
        jPanelCashFlowLayout.setVerticalGroup(
            jPanelCashFlowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCashFlowLayout.createSequentialGroup()
                .addComponent(jPanelControls, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Cash Flow", jPanelCashFlow);

        // --- bottom buttons ---
        jBPrint.setIcon(new javax.swing.ImageIcon(getClass().getResource("/at/redeye/FrameWork/base/resources/icons/print.png"))); // NOI18N
        jBPrint.setText("Print");
        jBPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBPrintActionPerformed(evt);
            }
        });

        jBClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/at/redeye/FrameWork/base/resources/icons/fileclose.gif"))); // NOI18N
        jBClose.setText("Close");
        jBClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCloseActionPerformed(evt);
            }
        });

        jBExportODT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/at/redeye/FrameWork/base/resources/icons/fileexport.gif"))); // NOI18N
        jBExportODT.setText("Export ODS");
        jBExportODT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBExportODTActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelButtonsLayout = new javax.swing.GroupLayout(jPanelButtons);
        jPanelButtons.setLayout(jPanelButtonsLayout);
        jPanelButtonsLayout.setHorizontalGroup(
            jPanelButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelButtonsLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jBPrint)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBExportODT)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBClose)
                .addContainerGap())
        );
        jPanelButtonsLayout.setVerticalGroup(
            jPanelButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelButtonsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBPrint)
                    .addComponent(jBExportODT)
                    .addComponent(jBClose))
                .addContainerGap())
        );

        // --- main layout ---
        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
            .addComponent(jPanelButtons, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanelButtons, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBGenerateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBGenerateActionPerformed
        generateReport();
    }//GEN-LAST:event_jBGenerateActionPerformed

    private void jBPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBPrintActionPerformed
        new AutoMBox(getTitle()) {
            @Override
            public void do_stuff() throws Exception {
                jReport.print();
            }
        };
    }//GEN-LAST:event_jBPrintActionPerformed

    private void jBCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCloseActionPerformed
        if (canClose()) {
            close();
        }
    }//GEN-LAST:event_jBCloseActionPerformed

    private void jBExportODTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBExportODTActionPerformed
        exportToODT();
    }//GEN-LAST:event_jBExportODTActionPerformed

    private void exportToODT() {
        if (jReport.getText() == null || jReport.getText().trim().isEmpty()) {
            return;
        }

        JFileChooser chooser = new JFileChooser(mainwin.getLastOpenPath());
        chooser.setDialogTitle("Export as ODS");
        chooser.setSelectedFile(new File("CashFlow.ods"));
        int result = chooser.showSaveDialog(this);
        if (result != JFileChooser.APPROVE_OPTION) {
            return;
        }

        final File targetFile;
        {
            File selected = chooser.getSelectedFile();
            if (!selected.getName().toLowerCase().endsWith(".ods")) {
                targetFile = new File(selected.getAbsolutePath() + ".ods");
            } else {
                targetFile = selected;
            }
            mainwin.setLastOpenPath(targetFile.getParent());
        }

        new AutoMBox("Export ODS") {
            @Override
            public void do_stuff() throws Exception {
                setWaitCursor();
                gui_to_var();
                double bankCash = parseBankCash();
                ReportCashFlowRenderer renderer =
                        new ReportCashFlowRenderer(getTransaction(), mainwin.getAZ(), bankCash, dateFrom, dateTill);
                renderer.collectData();
                String html = renderer.render();
                
                // Create ODS spreadsheet using odfdom
                org.odftoolkit.odfdom.doc.OdfSpreadsheetDocument spreadsheet = 
                        org.odftoolkit.odfdom.doc.OdfSpreadsheetDocument.newSpreadsheetDocument();
                
                // Get the first table
                java.util.List<org.odftoolkit.odfdom.doc.table.OdfTable> tables = spreadsheet.getSpreadsheetTables();
                org.odftoolkit.odfdom.doc.table.OdfTable table = tables.get(0);
                
                // Clear existing content
                java.util.List<org.odftoolkit.odfdom.doc.table.OdfTableRow> rows = table.getRowList();
                for (org.odftoolkit.odfdom.doc.table.OdfTableRow row : rows) {
                    table.removeRowsByIndex(row.getRowIndex(), 1);
                }
                
                // Add header row
                org.odftoolkit.odfdom.doc.table.OdfTableRow headerRow = table.appendRow();
                headerRow.getCellByIndex(0).setStringValue("Account Class");
                headerRow.getCellByIndex(1).setStringValue("Sum (€)");
                
                // Add data rows from renderer
                java.util.LinkedHashMap<Integer, String> acNames = renderer.getAccountClassNames();
                java.util.LinkedHashMap<Integer, Double> sumByClass = renderer.getSumByClass();
                
                for (java.util.Map.Entry<Integer, String> entry : acNames.entrySet()) {
                    int acIdx = entry.getKey();
                    double sum = sumByClass.getOrDefault(acIdx, 0.0);
                    if (sum == 0.0) {
                        continue;
                    }
                    org.odftoolkit.odfdom.doc.table.OdfTableRow dataRow = table.appendRow();
                    dataRow.getCellByIndex(0).setStringValue(entry.getValue());
                    dataRow.getCellByIndex(1).setDoubleValue(sum);
                }
                
                // Add total row
                org.odftoolkit.odfdom.doc.table.OdfTableRow totalRow = table.appendRow();
                totalRow.getCellByIndex(0).setStringValue("Total from booking lines");
                totalRow.getCellByIndex(1).setDoubleValue(renderer.getGrandTotal());
                
                // Add available cash row
                double available = bankCash + renderer.getGrandTotal();
                org.odftoolkit.odfdom.doc.table.OdfTableRow availableRow = table.appendRow();
                availableRow.getCellByIndex(0).setStringValue("Available cash (bank + total)");
                availableRow.getCellByIndex(1).setDoubleValue(available);
                
                // Add planned costs info if applicable
                double plannedCostsTotal = renderer.getPlannedCostsTotal();
                double paidTotalVal = renderer.getPaidTotal();
                if (plannedCostsTotal > 0 || paidTotalVal > 0) {
                    double plannedCostsMinusCosts = plannedCostsTotal - paidTotalVal;
                    org.odftoolkit.odfdom.doc.table.OdfTableRow costsRow = table.appendRow();
                    costsRow.getCellByIndex(0).setStringValue("Planned costs - Costs (for counting events)");
                    costsRow.getCellByIndex(1).setDoubleValue(plannedCostsMinusCosts);
                    
                    double estimatedIncome = available + plannedCostsMinusCosts;
                    org.odftoolkit.odfdom.doc.table.OdfTableRow estimatedRow = table.appendRow();
                    estimatedRow.getCellByIndex(0).setStringValue("Estimated income (available + planned - costs)");
                    estimatedRow.getCellByIndex(1).setDoubleValue(estimatedIncome);
                }
                
                try (FileOutputStream fos = new FileOutputStream(targetFile)) {
                    spreadsheet.save(fos);
                }
                setWaitCursor(false);
            }
        };
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBClose;
    private javax.swing.JButton jBExportODT;
    private at.redeye.Plugins.JDatePicker.JDatePicker jDateFrom;
    private at.redeye.Plugins.JDatePicker.JDatePicker jDateTill;
    private javax.swing.JButton jBGenerate;
    private javax.swing.JButton jBPrint;
    private javax.swing.JLabel jLabelBankCash;
    private javax.swing.JLabel jLabelDateFrom;
    private javax.swing.JLabel jLabelDateTill;
    private javax.swing.JPanel jPanelButtons;
    private javax.swing.JPanel jPanelCashFlow;
    private javax.swing.JPanel jPanelControls;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTBankCash;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextPane jReport;
    // End of variables declaration//GEN-END:variables
}
// AI-generated end
