/**
 * TwelveLittleScoutsClerk Cash Flow report dialog
 * @author Copyright (c) 2026 Martin Oberzalek
 */
// generated by AI (GitHub Copilot / Claude Sonnet 4.6)
package at.redeye.twelvelittlescoutsclerk.reports.cashflow;

import at.redeye.FrameWork.base.AutoMBox;
import at.redeye.FrameWork.base.BaseDialog;
import at.redeye.twelvelittlescoutsclerk.MainWin;
import at.redeye.twelvelittlescoutsclerk.reports.FixNimbusBackgroundColor;

// AI-generated start (GitHub Copilot / Claude Sonnet 4.6)
public class ReportCashFlow extends BaseDialog {

    private static final String CONFIG_BANK_CASH = ReportCashFlow.class.getName() + ".bankCash";

    private final MainWin mainwin;

    public ReportCashFlow(MainWin mainwin) {
        super(mainwin.getRoot(), "Cash Flow");
        this.mainwin = mainwin;
        initComponents();

        FixNimbusBackgroundColor.fixNimbusBackgroundColor(jReport);

        // restore last-used bank cash value
        String saved = root.getSetup().getLocalConfig(CONFIG_BANK_CASH, "0.0");
        jTBankCash.setText(saved);
    }

    @Override
    public void close() {
        root.getSetup().setLocalConfig(CONFIG_BANK_CASH, jTBankCash.getText().trim());
        super.close();
    }

    private double parseBankCash() {
        try {
            return Double.parseDouble(jTBankCash.getText().trim().replace(",", "."));
        } catch (NumberFormatException e) {
            return 0.0;
        }
    }

    private void generateReport() {
        new AutoMBox(getTitle()) {
            @Override
            public void do_stuff() throws Exception {
                setWaitCursor();
                double bankCash = parseBankCash();
                ReportCashFlowRenderer renderer =
                        new ReportCashFlowRenderer(getTransaction(), mainwin.getAZ(), bankCash);
                renderer.collectData();
                jReport.setText(renderer.render());
                jReport.setCaretPosition(0);
                setWaitCursor(false);
            }
        };
    }

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanelCashFlow = new javax.swing.JPanel();
        jPanelControls = new javax.swing.JPanel();
        jLabelBankCash = new javax.swing.JLabel();
        jTBankCash = new javax.swing.JTextField();
        jBGenerate = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jReport = new javax.swing.JTextPane();
        jPanelButtons = new javax.swing.JPanel();
        jBPrint = new javax.swing.JButton();
        jBClose = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

        // --- controls panel ---
        jLabelBankCash.setText("Current bank account cash (€):");

        jTBankCash.setColumns(12);

        jBGenerate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/at/redeye/FrameWork/base/resources/icons/reload.png"))); // NOI18N
        jBGenerate.setText("Generate Cash Flow");
        jBGenerate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBGenerateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelControlsLayout = new javax.swing.GroupLayout(jPanelControls);
        jPanelControls.setLayout(jPanelControlsLayout);
        jPanelControlsLayout.setHorizontalGroup(
            jPanelControlsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelControlsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelBankCash)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTBankCash, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jBGenerate)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelControlsLayout.setVerticalGroup(
            jPanelControlsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelControlsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelControlsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelBankCash)
                    .addComponent(jTBankCash, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBGenerate))
                .addContainerGap())
        );

        // --- report area ---
        jReport.setContentType("text/html");
        jReport.setEditable(false);
        jScrollPane1.setViewportView(jReport);

        // --- cash flow tab layout ---
        javax.swing.GroupLayout jPanelCashFlowLayout = new javax.swing.GroupLayout(jPanelCashFlow);
        jPanelCashFlow.setLayout(jPanelCashFlowLayout);
        jPanelCashFlowLayout.setHorizontalGroup(
            jPanelCashFlowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelControls, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1)
        );
        jPanelCashFlowLayout.setVerticalGroup(
            jPanelCashFlowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCashFlowLayout.createSequentialGroup()
                .addComponent(jPanelControls, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Cash Flow", jPanelCashFlow);

        // --- bottom buttons ---
        jBPrint.setIcon(new javax.swing.ImageIcon(getClass().getResource("/at/redeye/FrameWork/base/resources/icons/print.png"))); // NOI18N
        jBPrint.setText("Print");
        jBPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBPrintActionPerformed(evt);
            }
        });

        jBClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/at/redeye/FrameWork/base/resources/icons/fileclose.gif"))); // NOI18N
        jBClose.setText("Close");
        jBClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCloseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelButtonsLayout = new javax.swing.GroupLayout(jPanelButtons);
        jPanelButtons.setLayout(jPanelButtonsLayout);
        jPanelButtonsLayout.setHorizontalGroup(
            jPanelButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelButtonsLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jBPrint)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBClose)
                .addContainerGap())
        );
        jPanelButtonsLayout.setVerticalGroup(
            jPanelButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelButtonsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBPrint)
                    .addComponent(jBClose))
                .addContainerGap())
        );

        // --- main layout ---
        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
            .addComponent(jPanelButtons, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanelButtons, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBGenerateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBGenerateActionPerformed
        generateReport();
    }//GEN-LAST:event_jBGenerateActionPerformed

    private void jBPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBPrintActionPerformed
        new AutoMBox(getTitle()) {
            @Override
            public void do_stuff() throws Exception {
                jReport.print();
            }
        };
    }//GEN-LAST:event_jBPrintActionPerformed

    private void jBCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCloseActionPerformed
        if (canClose()) {
            close();
        }
    }//GEN-LAST:event_jBCloseActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBClose;
    private javax.swing.JButton jBGenerate;
    private javax.swing.JButton jBPrint;
    private javax.swing.JLabel jLabelBankCash;
    private javax.swing.JPanel jPanelButtons;
    private javax.swing.JPanel jPanelCashFlow;
    private javax.swing.JPanel jPanelControls;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTBankCash;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextPane jReport;
    // End of variables declaration//GEN-END:variables
}
// AI-generated end
