/**
 * TwelveLittleScoutsClerk Operational dialog for bulk booking-line operations
 * @author Copyright (c) 2026 Martin Oberzalek
 */
// generated by AI (GitHub Copilot / Claude Sonnet 4.6)
package at.redeye.twelvelittlescoutsclerk.dialog_operational;

import at.redeye.FrameWork.base.AutoMBox;
import at.redeye.FrameWork.base.BaseDialog;
import at.redeye.FrameWork.base.DefaultInsertOrUpdater;
import at.redeye.FrameWork.base.bindtypes.DBDateTime;
import at.redeye.FrameWork.base.tablemanipulator.TableManipulator;
import at.redeye.FrameWork.base.tablemanipulator.validators.DateValidator;
import at.redeye.FrameWork.base.transaction.Transaction;
import at.redeye.Plugins.JDatePicker.JDatePicker;
import at.redeye.SqlDBInterface.SqlDBIO.impl.TableBindingNotRegisteredException;
import at.redeye.SqlDBInterface.SqlDBIO.impl.UnsupportedDBDataTypeException;
import at.redeye.SqlDBInterface.SqlDBIO.impl.WrongBindFileFormatException;
import at.redeye.twelvelittlescoutsclerk.DateFilter;
import at.redeye.twelvelittlescoutsclerk.MainWin;
import at.redeye.twelvelittlescoutsclerk.bindtypes.DBAccountClasses;
import at.redeye.twelvelittlescoutsclerk.bindtypes.DBBookingLine;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JCheckBox;
import javax.swing.JComponent;

// AI-generated start (GitHub Copilot / Claude Sonnet 4.6)
public class Operational extends BaseDialog {

    /** Wraps a DBAccountClasses entry (or a special sentinel) for combo items. */
    static class AccountClassDescr {
        public final int filterIdx;
        private final String label;
        public final DBAccountClasses accountClass; // null for sentinel items

        public AccountClassDescr(String label, int filterIdx, DBAccountClasses accountClass) {
            this.label = label;
            this.filterIdx = filterIdx;
            this.accountClass = accountClass;
        }

        @Override
        public String toString() {
            return label;
        }
    }

    MainWin mainwin;
    List<DBBookingLine> values;
    TableManipulator tm;
    DBDateTime filter_date_from = new DBDateTime("dummy");
    DBDateTime filter_date_till = new DBDateTime("dummy");
    ArrayList<JComponent> filters = new ArrayList<>();

    public Operational(MainWin mainwin) {
        super(mainwin.getRoot(), "Operational");

        initComponents();

        this.mainwin = mainwin;

        DBBookingLine bookinglines = new DBBookingLine();

        tm = new TableManipulator(root, jTContent, bookinglines);

        tm.hide(bookinglines.hist.lo_user);
        tm.hide(bookinglines.hist.lo_zeit);
        tm.hide(bookinglines.hist.ae_user);
        tm.hide(bookinglines.hist.an_user);
        tm.hide(bookinglines.hist.an_zeit);
        tm.hide(bookinglines.hist.ae_zeit);
        tm.hide(bookinglines.bp_idx);

        tm.setValidator(bookinglines.hist.ae_zeit, new DateValidator());
        tm.setValidator(bookinglines.hist.an_zeit, new DateValidator());

        tm.prepareTable();

        // enable multi-selection
        jTContent.setSelectionMode(javax.swing.ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);

        bindVar(jDateFrom, filter_date_from);
        bindVar(jDateTill, filter_date_till);

        jDateFrom.setTextEditable(true);
        jDateTill.setTextEditable(true);

        filters.add(jCIn);
        filters.add(jCOut);
        filters.add(jCAssigned);
        filters.add(jCUnassigned);
        filters.add(jCFrom);
        filters.add(jCTill);
        filters.add(jDateFrom);
        filters.add(jDateTill);
        filters.add(jCAccountClassFilter);

        new AutoMBox(getTitle(), false) {
            @Override
            public void do_stuff() throws Exception {
                populateAccountClassFilter();
                populateAccountClassAssign();
            }
        };

        for (int i = 0; i < filters.size(); i++) {
            String check_filter = getUniqueDialogIdentifier("Filter").concat(String.format(".Filter[%d]", i));
            JComponent comp = filters.get(i);

            if (comp instanceof JCheckBox) {
                JCheckBox check = (JCheckBox) comp;
                if (Boolean.parseBoolean(root.getSetup().getLocalConfig(check_filter, "False"))) {
                    check.setSelected(true);
                }
            } else if (comp instanceof JDatePicker) {
                JDatePicker date = (JDatePicker) comp;
                date.setDate(root.getSetup().getLocalConfig(check_filter, ""));
            } else if (comp instanceof javax.swing.JComboBox) {
                @SuppressWarnings("unchecked")
                javax.swing.JComboBox<AccountClassDescr> combo = (javax.swing.JComboBox<AccountClassDescr>) comp;
                String savedIdx = root.getSetup().getLocalConfig(check_filter, "0");
                restoreAccountClassFilter(combo, savedIdx);
            }
        }

        filter_date_from.loadFromString("1970-01-01 00:00:00");
        filter_date_till.loadFromString("1970-01-01 00:00:00");

        gui_to_var();
        feed_table(false);
        tm.autoResize();
        tableFilter1.setFilter(jTContent);
    }

    @Override
    public void close() {
        for (int i = 0; i < filters.size(); i++) {
            JComponent comp = filters.get(i);
            String check_filter = getUniqueDialogIdentifier("Filter").concat(String.format(".Filter[%d]", i));

            if (comp instanceof JCheckBox) {
                JCheckBox check = (JCheckBox) comp;
                root.getSetup().setLocalConfig(check_filter, Boolean.toString(check.isSelected()));
            } else if (comp instanceof JDatePicker) {
                JDatePicker date = (JDatePicker) comp;
                root.getSetup().setLocalConfig(check_filter, date.getDate());
            } else if (comp instanceof javax.swing.JComboBox) {
                @SuppressWarnings("unchecked")
                javax.swing.JComboBox<AccountClassDescr> combo = (javax.swing.JComboBox<AccountClassDescr>) comp;
                AccountClassDescr selected = (AccountClassDescr) combo.getSelectedItem();
                String savedIdx = (selected != null) ? String.valueOf(selected.filterIdx) : "0";
                root.getSetup().setLocalConfig(check_filter, savedIdx);
            }
        }
        super.close();
    }

    private void feed_table() {
        feed_table(true);
    }

    private void feed_table(boolean autombox) {
        new AutoMBox(getTitle(), autombox) {
            @Override
            public void do_stuff() throws Exception {
                tm.clear();

                DBBookingLine bookingline = new DBBookingLine();
                Transaction trans = getTransaction();

                StringBuilder sql = new StringBuilder();
                sql.append("where ").append(trans.markColumn(bookingline.bp_idx)).append(" = ").append(mainwin.getBPIdx());
                sql.append(" and ").append(trans.markColumn(bookingline.splitpos)).append(" = 0 ");

                if (jCIn.isSelected()) {
                    sql.append(" and ").append(trans.markColumn(bookingline.amount)).append(" >= 0 ");
                }
                if (jCOut.isSelected()) {
                    sql.append(" and ").append(trans.markColumn(bookingline.amount)).append(" <= 0 ");
                }
                if (jCUnassigned.isSelected()) {
                    sql.append(" and ").append(trans.markColumn(bookingline.assigned)).append(" = 0 ");
                }
                if (jCAssigned.isSelected()) {
                    sql.append(" and ").append(trans.markColumn(bookingline.assigned)).append(" = 1 ");
                }

                sql.append(DateFilter.getVonBisFilter(trans,
                        jCFrom.isSelected() ? filter_date_from : null,
                        jCTill.isSelected() ? filter_date_till : null,
                        bookingline.date));

                AccountClassDescr acFilter = (AccountClassDescr) jCAccountClassFilter.getSelectedItem();
                if (acFilter != null) {
                    if (acFilter.filterIdx == -1) {
                        sql.append(" and ").append(trans.markColumn(bookingline.account_class_idx)).append(" = 0 ");
                    } else if (acFilter.filterIdx > 0) {
                        sql.append(" and ").append(trans.markColumn(bookingline.account_class_idx)).append(" = ").append(acFilter.filterIdx).append(" ");
                    }
                }

                sql.append(" order by ").append(trans.markColumn(bookingline.date));

                values = trans.fetchTable2(bookingline, sql.toString());

                for (DBBookingLine entry : values) {
                    tm.add(entry);
                }
            }
        };
    }

    private void populateAccountClassFilter()
            throws SQLException, TableBindingNotRegisteredException,
                   UnsupportedDBDataTypeException, WrongBindFileFormatException {
        jCAccountClassFilter.removeAllItems();
        jCAccountClassFilter.addItem(new AccountClassDescr("unassigned", -1, null));
        jCAccountClassFilter.addItem(new AccountClassDescr("any", 0, null));

        Transaction trans = getTransaction();
        DBAccountClasses acClass = new DBAccountClasses();
        List<DBAccountClasses> classes = trans.fetchTable2(acClass,
                "where " + trans.markColumn(acClass, acClass.bp_idx) + " = " + mainwin.getBPIdx()
                + " order by " + trans.markColumn(acClass, acClass.name));

        for (DBAccountClasses ac : classes) {
            jCAccountClassFilter.addItem(new AccountClassDescr(ac.name.toString(), ac.idx.getValue(), ac));
        }
        jCAccountClassFilter.setSelectedIndex(1); // default: "any"
    }

    private void populateAccountClassAssign()
            throws SQLException, TableBindingNotRegisteredException,
                   UnsupportedDBDataTypeException, WrongBindFileFormatException {
        jCAccountClassAssign.removeAllItems();
        jCAccountClassAssign.addItem(new AccountClassDescr("(none)", 0, null));

        Transaction trans = getTransaction();
        DBAccountClasses acClass = new DBAccountClasses();
        List<DBAccountClasses> classes = trans.fetchTable2(acClass,
                "where " + trans.markColumn(acClass, acClass.bp_idx) + " = " + mainwin.getBPIdx()
                + " order by " + trans.markColumn(acClass, acClass.name));

        for (DBAccountClasses ac : classes) {
            jCAccountClassAssign.addItem(new AccountClassDescr(ac.name.toString(), ac.idx.getValue(), ac));
        }
    }

    private void restoreAccountClassFilter(
            javax.swing.JComboBox<AccountClassDescr> combo, String savedIdx) {
        try {
            int idx = Integer.parseInt(savedIdx);
            for (int i = 0; i < combo.getItemCount(); i++) {
                AccountClassDescr item = combo.getItemAt(i);
                if (item != null && item.filterIdx == idx) {
                    combo.setSelectedIndex(i);
                    return;
                }
            }
        } catch (NumberFormatException ignored) {}
        if (combo.getItemCount() > 1) {
            combo.setSelectedIndex(1);
        }
    }

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTContent = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLInfo = new javax.swing.JLabel();
        tableFilter1 = new at.redeye.twelvelittlescoutsclerk.tableFilter();
        jCOut = new javax.swing.JCheckBox();
        jCIn = new javax.swing.JCheckBox();
        jCUnassigned = new javax.swing.JCheckBox();
        jCAssigned = new javax.swing.JCheckBox();
        jCFrom = new javax.swing.JCheckBox();
        jDateFrom = new at.redeye.Plugins.JDatePicker.JDatePicker();
        jCTill = new javax.swing.JCheckBox();
        jDateTill = new at.redeye.Plugins.JDatePicker.JDatePicker();
        jLAccountClass = new javax.swing.JLabel();
        jCAccountClassFilter = new javax.swing.JComboBox<>();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanelAssignTab = new javax.swing.JPanel();
        jLabelAssignClass = new javax.swing.JLabel();
        jCAccountClassAssign = new javax.swing.JComboBox<>();
        jBAssign = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jBClose = new javax.swing.JButton();
        jBRefresh = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

        jTContent.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTContent);

        // --- filter panel (jPanel4) ---
        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setText("Operational");

        jLInfo.setText(" ");
        jLInfo.setAutoscrolls(true);

        jCOut.setText("Outgoing");
        jCOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCOutActionPerformed(evt);
            }
        });

        jCIn.setText("Incoming");
        jCIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCInActionPerformed(evt);
            }
        });

        jCUnassigned.setText("unassigned");
        jCUnassigned.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCUnassignedActionPerformed(evt);
            }
        });

        jCAssigned.setText("assigned");
        jCAssigned.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCAssignedActionPerformed(evt);
            }
        });

        jCFrom.setText("From");
        jCFrom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCFromActionPerformed(evt);
            }
        });

        jDateFrom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jDateFromActionPerformed(evt);
            }
        });

        jCTill.setText("Till");
        jCTill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCTillActionPerformed(evt);
            }
        });

        jDateTill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jDateTillActionPerformed(evt);
            }
        });

        jLAccountClass.setText("Account class:");

        jCAccountClassFilter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCAccountClassFilterActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCAssigned)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCUnassigned)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCIn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCOut)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tableFilter1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jCFrom)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jDateFrom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCTill)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jDateTill, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLAccountClass)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCAccountClassFilter, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jCFrom)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel1)
                                .addComponent(jCOut)
                                .addComponent(jCIn)
                                .addComponent(jCUnassigned)
                                .addComponent(jCAssigned)
                                .addComponent(jLInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(tableFilter1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jDateFrom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jDateTill, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jCAccountClassFilter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jCTill)
                            .addComponent(jLAccountClass))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        // --- tab panel: Account Class Assignment ---
        jLabelAssignClass.setText("Account class:");

        jBAssign.setIcon(new javax.swing.ImageIcon(getClass().getResource("/at/redeye/FrameWork/base/resources/icons/button_ok.gif"))); // NOI18N
        jBAssign.setText("Assign to selection");
        jBAssign.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAssignActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelAssignTabLayout = new javax.swing.GroupLayout(jPanelAssignTab);
        jPanelAssignTab.setLayout(jPanelAssignTabLayout);
        jPanelAssignTabLayout.setHorizontalGroup(
            jPanelAssignTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAssignTabLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelAssignClass)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCAccountClassAssign, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jBAssign)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelAssignTabLayout.setVerticalGroup(
            jPanelAssignTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAssignTabLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelAssignTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelAssignClass)
                    .addComponent(jCAccountClassAssign, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBAssign))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Account Class Assignment", jPanelAssignTab);

        // --- bottom button panel ---
        jBClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/at/redeye/FrameWork/base/resources/icons/fileclose.gif"))); // NOI18N
        jBClose.setText("Close");
        jBClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCloseActionPerformed(evt);
            }
        });

        jBRefresh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/at/redeye/FrameWork/base/resources/icons/button_read.gif"))); // NOI18N
        jBRefresh.setText("Refresh");
        jBRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBRefreshActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jBRefresh)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jBClose)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBRefresh)
                    .addComponent(jBClose))
                .addContainerGap())
        );

        // --- content pane layout ---
        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(jScrollPane1)
            .addComponent(jTabbedPane1)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCloseActionPerformed
        if (canClose()) {
            close();
        }
    }//GEN-LAST:event_jBCloseActionPerformed

    private void jBRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBRefreshActionPerformed
        feed_table(true);
    }//GEN-LAST:event_jBRefreshActionPerformed

    private void jCInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCInActionPerformed
        feed_table(true);
    }//GEN-LAST:event_jCInActionPerformed

    private void jCOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCOutActionPerformed
        feed_table(true);
    }//GEN-LAST:event_jCOutActionPerformed

    private void jCAssignedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCAssignedActionPerformed
        feed_table(true);
    }//GEN-LAST:event_jCAssignedActionPerformed

    private void jCUnassignedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCUnassignedActionPerformed
        feed_table(true);
    }//GEN-LAST:event_jCUnassignedActionPerformed

    private void jCFromActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCFromActionPerformed
        feed_table(true);
    }//GEN-LAST:event_jCFromActionPerformed

    private void jCTillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCTillActionPerformed
        feed_table(true);
    }//GEN-LAST:event_jCTillActionPerformed

    private void jDateFromActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jDateFromActionPerformed
        gui_to_var();
        feed_table(true);
    }//GEN-LAST:event_jDateFromActionPerformed

    private void jDateTillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jDateTillActionPerformed
        gui_to_var();
        feed_table(true);
    }//GEN-LAST:event_jDateTillActionPerformed

    private void jCAccountClassFilterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCAccountClassFilterActionPerformed
        feed_table(true);
    }//GEN-LAST:event_jCAccountClassFilterActionPerformed

    private void jBAssignActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAssignActionPerformed
        AccountClassDescr descr = (AccountClassDescr) jCAccountClassAssign.getSelectedItem();
        if (descr == null) {
            return;
        }

        int[] selectedViewRows = jTContent.getSelectedRows();
        if (selectedViewRows.length == 0) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "No rows selected.", "Info", javax.swing.JOptionPane.INFORMATION_MESSAGE);
            return;
        }

        // convert view rows to model rows before any table refresh
        int[] modelRows = new int[selectedViewRows.length];
        for (int i = 0; i < selectedViewRows.length; i++) {
            modelRows[i] = jTContent.convertRowIndexToModel(selectedViewRows[i]);
        }

        new AutoMBox(getTitle()) {
            @Override
            public void do_stuff() throws Exception {
                Transaction trans = getTransaction();
                for (int modelRow : modelRows) {
                    if (modelRow < 0 || modelRow >= values.size()) {
                        continue;
                    }
                    DBBookingLine bl = values.get(modelRow);
                    if (descr.accountClass != null) {
                        bl.account_class_idx.loadFromCopy(descr.accountClass.idx.getValue());
                        bl.account_class.loadFromString(descr.accountClass.name.toString());
                    } else {
                        bl.account_class_idx.loadFromCopy(0);
                        bl.account_class.loadFromString("");
                    }
                    DefaultInsertOrUpdater.insertOrUpdateValuesWithPrimKey(trans, bl);
                }
                trans.commit();
                feed_table(false);
            }
        };
    }//GEN-LAST:event_jBAssignActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBAssign;
    private javax.swing.JButton jBClose;
    private javax.swing.JButton jBRefresh;
    private javax.swing.JComboBox<AccountClassDescr> jCAccountClassAssign;
    private javax.swing.JComboBox<AccountClassDescr> jCAccountClassFilter;
    private javax.swing.JCheckBox jCAssigned;
    private javax.swing.JCheckBox jCFrom;
    private javax.swing.JCheckBox jCIn;
    private javax.swing.JCheckBox jCOut;
    private javax.swing.JCheckBox jCTill;
    private javax.swing.JCheckBox jCUnassigned;
    private at.redeye.Plugins.JDatePicker.JDatePicker jDateFrom;
    private at.redeye.Plugins.JDatePicker.JDatePicker jDateTill;
    private javax.swing.JLabel jLAccountClass;
    private javax.swing.JLabel jLInfo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelAssignClass;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanelAssignTab;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTContent;
    private javax.swing.JTabbedPane jTabbedPane1;
    private at.redeye.twelvelittlescoutsclerk.tableFilter tableFilter1;
    // End of variables declaration//GEN-END:variables
}
// AI-generated end
