/**
 * TwelveLittleScoutsClerk EPC QR code generation helper (SEPA Credit Transfer / Girocode)
 * @author Copyright (c) 2023-2026 Martin Oberzalek
 */
package at.redeye.twelvelittlescoutsclerk;

import com.google.zxing.BarcodeFormat;
import com.google.zxing.EncodeHintType;
import com.google.zxing.WriterException;
import com.google.zxing.client.j2se.MatrixToImageWriter;
import com.google.zxing.common.BitMatrix;
import com.google.zxing.qrcode.QRCodeWriter;
import com.google.zxing.qrcode.decoder.ErrorCorrectionLevel;
import java.awt.image.BufferedImage;
import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.util.EnumMap;
import java.util.Map;
import javax.imageio.ImageIO;

// generated by AI (Claude Sonnet 4.6)
public class EpcQrHelper {

    private static final String EPC_VERSION = "002";
    private static final String CHARACTER_SET = "1"; // UTF-8
    private static final String IDENTIFICATION = "SCT";

    /**
     * Builds the EPC QR code payload string (LF-delimited, 12 lines).
     * See https://en.wikipedia.org/wiki/EPC_QR_code for the full specification.
     *
     * @param beneficiaryName          Name of the payee (max 70 chars)
     * @param iban                     IBAN of the payee — spaces are stripped automatically
     * @param bic                      BIC of the payee's bank; pass {@code ""} for v002 (optional)
     * @param amountEur                Amount in EUR; &lt;= 0 means "unspecified"
     * @param remittanceUnstructured   Free-text payment reference (max 140 chars)
     * @param purposeCode              4-char ISO 20022 purpose code (e.g. "CHAR"); {@code ""} to omit
     * @return the EPC payload string ready to be encoded into a QR code
     */
    // generated by AI (Claude Sonnet 4.6)
    public static String buildEpcPayload(String beneficiaryName, String iban,
            String bic, double amountEur, String remittanceUnstructured,
            String purposeCode) {

        if (beneficiaryName == null || beneficiaryName.isBlank()) {
            throw new IllegalArgumentException("Beneficiary name is required");
        }
        if (beneficiaryName.length() > 70) {
            beneficiaryName = beneficiaryName.substring(0, 70);
        }
        if (iban == null || iban.isBlank()) {
            throw new IllegalArgumentException("IBAN is required");
        }

        String cleanIban = iban.replaceAll("\\s+", "");
        String amountStr = amountEur > 0.0 ? String.format("EUR%.2f", amountEur) : "";
        String safeBic = bic == null ? "" : bic.trim();
        String safePurpose = purposeCode == null ? "" : purposeCode.trim();
        String safeRemittance = remittanceUnstructured == null ? "" : remittanceUnstructured.trim();
        if (safeRemittance.length() > 140) {
            safeRemittance = safeRemittance.substring(0, 140);
        }

        // 12-line EPC payload (LF separated):
        // BCD / version / charset / SCT / BIC / name / IBAN / amount /
        // purpose / structured-ref (blank) / unstructured-ref / beneficiary-info (blank)
        return "BCD\n"
                + EPC_VERSION + "\n"
                + CHARACTER_SET + "\n"
                + IDENTIFICATION + "\n"
                + safeBic + "\n"
                + beneficiaryName + "\n"
                + cleanIban + "\n"
                + amountStr + "\n"
                + safePurpose + "\n"
                + "\n"
                + safeRemittance + "\n"
                + "";
    }

    /**
     * Encodes an EPC payload string as a QR code image.
     * Error correction level M is used as required by the EPC specification.
     *
     * @param epcPayload  the string returned by {@link #buildEpcPayload}
     * @param sizePixels  width and height of the resulting square image in pixels
     * @return a {@link BufferedImage} containing the QR code
     * @throws WriterException if ZXing cannot encode the payload
     */
    // generated by AI (Claude Sonnet 4.6)
    public static BufferedImage generateQrImage(String epcPayload, int sizePixels)
            throws WriterException {

        Map<EncodeHintType, Object> hints = new EnumMap<>(EncodeHintType.class);
        hints.put(EncodeHintType.ERROR_CORRECTION, ErrorCorrectionLevel.M);
        hints.put(EncodeHintType.CHARACTER_SET, "UTF-8");
        hints.put(EncodeHintType.MARGIN, 1);

        QRCodeWriter writer = new QRCodeWriter();
        BitMatrix matrix = writer.encode(epcPayload, BarcodeFormat.QR_CODE,
                sizePixels, sizePixels, hints);
        return MatrixToImageWriter.toBufferedImage(matrix);
    }

    /**
     * Encodes an EPC payload string as a PNG byte array.
     *
     * @param epcPayload  the string returned by {@link #buildEpcPayload}
     * @param sizePixels  width and height of the resulting square image in pixels
     * @return PNG-encoded bytes of the QR code
     * @throws WriterException if ZXing cannot encode the payload
     * @throws IOException     if PNG encoding fails
     */
    // generated by AI (Claude Sonnet 4.6)
    public static byte[] generateQrPng(String epcPayload, int sizePixels)
            throws WriterException, IOException {

        BufferedImage img = generateQrImage(epcPayload, sizePixels);
        ByteArrayOutputStream bos = new ByteArrayOutputStream();
        ImageIO.write(img, "PNG", bos);
        return bos.toByteArray();
    }

    /**
     * Convenience method: generates an EPC QR code PNG using the organisation's
     * IBAN and name from {@link AppConfigDefinitions} (no BIC, EPC v002).
     *
     * @param amountEur   amount in EUR; pass 0.0 or negative to leave unspecified
     * @param remittance  free-text payment reference shown to the payer (max 140 chars)
     * @param sizePixels  image size in pixels (e.g. 300)
     * @return PNG-encoded bytes of the QR code
     * @throws WriterException if ZXing cannot encode
     * @throws IOException     if PNG encoding fails
     */
    // generated by AI (Claude Sonnet 4.6)
    public static byte[] generateBillQrPng(double amountEur, String remittance, int sizePixels)
            throws WriterException, IOException {

        String name = AppConfigDefinitions.Organisation.getConfigValue();
        String iban = AppConfigDefinitions.OrganisaiontIBAN.getConfigValue();
        String payload = buildEpcPayload(name, iban, "", amountEur, remittance, "");
        return generateQrPng(payload, sizePixels);
    }
}
