/**
 * TwelveLittleScoutsClerk background worker: syncs bills to a folder
 * @author Copyright (c) 2023-2026 Martin Oberzalek
 */
// generated by AI (GitHub Copilot / Claude Sonnet 4.6)
package at.redeye.twelvelittlescoutsclerk;

import at.redeye.FrameWork.base.Root;
import at.redeye.FrameWork.base.transaction.Transaction;
import at.redeye.twelvelittlescoutsclerk.bindtypes.DBBill;
import at.redeye.twelvelittlescoutsclerk.bindtypes.DBEventMember;
import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import org.apache.log4j.Logger;

public class SyncBillsWorker implements Runnable {

    private static final Logger logger = Logger.getLogger(SyncBillsWorker.class.getName());

    private static final int POLL_INTERVAL_MS = 30_000;

    private final Transaction trans;
    private final Root root;

    public SyncBillsWorker(Root root, Transaction trans) {
        this.root = root;
        this.trans = trans;
    }

    @Override
    public void run() {
        while (!Thread.currentThread().isInterrupted()) {
            try {
                syncBills();
                Thread.sleep(POLL_INTERVAL_MS);
            } catch (InterruptedException e) {
                Thread.currentThread().interrupt();
            } catch (Exception ex) {
                logger.error("SyncBillsWorker cycle failed", ex);
                try {
                    Thread.sleep(POLL_INTERVAL_MS);
                } catch (InterruptedException ie) {
                    Thread.currentThread().interrupt();
                }
            }
        }
    }

    private void syncBills() throws Exception {
        String folderPath = root.getSetup().getLocalConfig(AppConfigDefinitions.SyncBillsFolder.getConfigName(), "");
        if (folderPath == null || folderPath.trim().isEmpty()) {
            return; // not configured
        }

        folderPath = folderPath.trim();
        Path targetDir = Paths.get(folderPath);
        if (!Files.isDirectory(targetDir)) {
            logger.warn("SyncBillsFolder is not a valid directory: " + folderPath);
            return;
        }

        List<DBBill> bills = fetchValidBills();
        if (bills.isEmpty()) {
            return;
        }

        for (DBBill bill : bills) {
            try {
                syncBill(bill, targetDir);
            } catch (Exception ex) {
                logger.warn("Failed to sync bill " + bill.billingnr.getValue(), ex);
            }
        }
    }

    private List<DBBill> fetchValidBills() throws Exception {
        DBBill proto = new DBBill();
        return trans.fetchTable2(proto,
                "where " + trans.markColumn(proto.state) + " = "
                + DBBill.State.NORMAL.ordinal()
                + " and " + trans.markColumn(proto.direction) + " = "
                + DBBill.Direction.OUTGOING.ordinal()
                + " and " + trans.markColumn(proto.pdf_data) + " is not null"
                + " order by " + trans.markColumn(proto.idx));
    }

    private void syncBill(DBBill bill, Path targetDir) throws Exception {
        // Determine member name: look up via DBEventMember
        String memberName = resolveMemberName(bill);
        if (memberName == null || memberName.trim().isEmpty()) {
            memberName = "unknown";
        }
        // Sanitize: replace characters unsafe for filenames
        memberName = sanitizeFileName(memberName);

        // Build date part from hist.an_zeit (creation timestamp)
        String datePart = formatDate(bill.hist.an_zeit.getValue());

        // Build billing number
        String billingNr = bill.billingnr.getValue();
        if (billingNr == null || billingNr.trim().isEmpty()) {
            billingNr = "no-nr";
        }

        // File name: YYYY-MM-DD Rechnung-{billingnr}-{member_name}.pdf
        String fileName = datePart + " Rechnung-" + billingNr + "-" + memberName + ".pdf";
        File targetFile = targetDir.resolve(fileName).toFile();

        // Skip if already exists
        if (targetFile.exists()) {
            return;
        }

        // Write PDF data
        byte[] pdfData = bill.pdf_data.value;
        if (pdfData == null || pdfData.length == 0) {
            return;
        }

        try (FileOutputStream fos = new FileOutputStream(targetFile)) {
            fos.write(pdfData);
        }
        logger.info("Synced bill to: " + targetFile.getAbsolutePath());
    }

    /**
     * Resolve the member name associated with this bill.
     * Looks up DBEventMember by bill_idx (or registration_bill_idx for registration bills).
     */
    private String resolveMemberName(DBBill bill) throws Exception {
        DBEventMember proto = new DBEventMember();

        List<DBEventMember> members;
        if (bill.isRegistration()) {
            members = trans.fetchTable2(proto,
                    "where " + trans.markColumn(proto.registration_bill_idx) + " = " + bill.idx.getValue());
        } else {
            members = trans.fetchTable2(proto,
                    "where " + trans.markColumn(proto.bill_idx) + " = " + bill.idx.getValue());
        }

        if (members.isEmpty()) {
            return null;
        }

        DBEventMember em = members.get(0);
        String forname = em.forname.getValue();
        String name = em.name.getValue();

        if (forname != null && !forname.trim().isEmpty() && name != null && !name.trim().isEmpty()) {
            return forname.trim() + " " + name.trim();
        } else if (name != null && !name.trim().isEmpty()) {
            return name.trim();
        } else if (forname != null && !forname.trim().isEmpty()) {
            return forname.trim();
        }
        return null;
    }

    private String formatDate(Date date) {
        if (date == null) {
            return "0000-00-00";
        }
        // AI-generated start (GitHub Copilot / Claude Sonnet 4.6)
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        return sdf.format(date);
        // AI-generated end
    }

    private String sanitizeFileName(String name) {
        if (name == null) {
            return "";
        }
        // Replace characters illegal in file names on Windows/Linux
        // AI-generated start (GitHub Copilot / Claude Sonnet 4.6)
        return name.replaceAll("[\\\\/:*?\"<>|]", "_")
                   .replaceAll("\\s+", "_")
                   .trim();
        // AI-generated end
    }
}
// AI-generated end
