/**
 * TwelveLittleScoutsClerk Edit dialog for BillTemplate
 * @author Copyright (c) 2023-2026 Martin Oberzalek
 */
package at.redeye.twelvelittlescoutsclerk.dialog_billingtemplate;

import at.redeye.FrameWork.base.AutoMBox;
import at.redeye.FrameWork.base.BaseDialogDialog;
import at.redeye.FrameWork.base.DefaultInsertOrUpdater;
import at.redeye.FrameWork.base.transaction.Transaction;
import at.redeye.FrameWork.base.bindtypes.DBString;
import at.redeye.FrameWork.widgets.documentfields.DocumentFieldLimit;
import at.redeye.twelvelittlescoutsclerk.MainWin;
import at.redeye.twelvelittlescoutsclerk.bindtypes.DBBillTemplate;
import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import java.nio.file.Files;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author martin
 */
// generated by AI (Claude Sonnet 4.6)
public class EditBillingTemplate extends BaseDialogDialog {

    DBBillTemplate entity;
    MainWin mainwin;
    boolean saved = false;

    public EditBillingTemplate(MainWin mainwin, DBBillTemplate entity) {
        super(mainwin.getRoot(), "Abrechnungsvorlage bearbeiten");
        initComponents();

        this.entity = entity;
        this.mainwin = mainwin;

        bindVar(jTName, entity.name);
        bindVar(jTDescription, entity.description);

        var_to_gui();

        updateFileNameLabel();
        updateDownloadButton();

        if (mainwin.isAzLocked()) {
            jBSave.setEnabled(false);
            jBUpload.setEnabled(false);
        }
    }

    private void updateFileNameLabel() {
        String fn = entity.file_name.toString();
        jLFileName.setText(fn.isEmpty() ? "(keine Datei)" : fn);
    }

    private void updateDownloadButton() {
        jBDownload.setEnabled(entity.odt_data.value != null && entity.odt_data.value.length > 0);
    }

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelName = new javax.swing.JLabel();
        jTName = new javax.swing.JTextField();
        jLabelDescription = new javax.swing.JLabel();
        jTDescription = new javax.swing.JTextField();
        jLabelFile = new javax.swing.JLabel();
        jLFileName = new javax.swing.JLabel();
        jPanelButtons = new javax.swing.JPanel();
        jBUpload = new javax.swing.JButton();
        jBDownload = new javax.swing.JButton();
        jPanelActions = new javax.swing.JPanel();
        jBSave = new javax.swing.JButton();
        jBClose = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(548, 300));

        jLabelName.setText("Name:");

        jLabelDescription.setText("Beschreibung:");

        jLabelFile.setText("Datei:");

        jLFileName.setText("(keine Datei)");

        jBUpload.setIcon(new javax.swing.ImageIcon(getClass().getResource("/at/redeye/FrameWork/base/resources/icons/bookmark.png"))); // NOI18N
        jBUpload.setText("Hochladen");
        jBUpload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBUploadActionPerformed(evt);
            }
        });

        jBDownload.setIcon(new javax.swing.ImageIcon(getClass().getResource("/at/redeye/FrameWork/base/resources/icons/fileclose.gif"))); // NOI18N
        jBDownload.setText("Herunterladen");
        jBDownload.setEnabled(false);
        jBDownload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBDownloadActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelButtonsLayout = new javax.swing.GroupLayout(jPanelButtons);
        jPanelButtons.setLayout(jPanelButtonsLayout);
        jPanelButtonsLayout.setHorizontalGroup(
            jPanelButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelButtonsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jBUpload)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBDownload)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelButtonsLayout.setVerticalGroup(
            jPanelButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelButtonsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBUpload)
                    .addComponent(jBDownload))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jBSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/at/redeye/FrameWork/base/resources/icons/button_ok.gif"))); // NOI18N
        jBSave.setText("Speichern");
        jBSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSaveActionPerformed(evt);
            }
        });

        jBClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/at/redeye/FrameWork/base/resources/icons/fileclose.gif"))); // NOI18N
        jBClose.setText("Schließen");
        jBClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCloseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelActionsLayout = new javax.swing.GroupLayout(jPanelActions);
        jPanelActions.setLayout(jPanelActionsLayout);
        jPanelActionsLayout.setHorizontalGroup(
            jPanelActionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelActionsLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jBSave)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBClose)
                .addContainerGap())
        );
        jPanelActionsLayout.setVerticalGroup(
            jPanelActionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelActionsLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelActionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBSave)
                    .addComponent(jBClose))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelActions, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanelButtons, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelFile)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLFileName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelDescription)
                            .addComponent(jLabelName))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTName)
                            .addComponent(jTDescription))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelName)
                    .addComponent(jTName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelDescription)
                    .addComponent(jTDescription, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelFile)
                    .addComponent(jLFileName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelButtons, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanelActions, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBUploadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBUploadActionPerformed

        JFileChooser chooser = new JFileChooser(mainwin.getLastOpenPath());
        chooser.setDialogTitle("Vorlage hochladen");
        int result = chooser.showOpenDialog(this);
        if (result != JFileChooser.APPROVE_OPTION) {
            return;
        }

        File selected = chooser.getSelectedFile();
        mainwin.setLastOpenPath(selected.getParent());

        new AutoMBox(EditBillingTemplate.class.getName()) {
            @Override
            public void do_stuff() throws Exception {
                byte[] data = Files.readAllBytes(selected.toPath());
                entity.odt_data.value = data;
                entity.file_name.loadFromString(selected.getName());
                if (entity.name.toString().trim().isEmpty()) {
                    String nameWithoutExt = selected.getName().replaceFirst("\\.[^.]+$", "");
                    entity.name.loadFromString(nameWithoutExt);
                    var_to_gui();
                }
                updateFileNameLabel();
                updateDownloadButton();
            }
        };

    }//GEN-LAST:event_jBUploadActionPerformed

    private void jBDownloadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBDownloadActionPerformed

        if (entity.odt_data.value == null || entity.odt_data.value.length == 0) {
            return;
        }

        JFileChooser chooser = new JFileChooser(mainwin.getLastOpenPath());
        chooser.setDialogTitle("Vorlage speichern");
        chooser.setSelectedFile(new File(entity.file_name.toString()));
        int result = chooser.showSaveDialog(this);
        if (result != JFileChooser.APPROVE_OPTION) {
            return;
        }

        File target = chooser.getSelectedFile();
        mainwin.setLastOpenPath(target.getParent());

        new AutoMBox(EditBillingTemplate.class.getName()) {
            @Override
            public void do_stuff() throws Exception {
                try (FileOutputStream fos = new FileOutputStream(target)) {
                    fos.write(entity.odt_data.value);
                }
            }
        };

    }//GEN-LAST:event_jBDownloadActionPerformed

    private void jBSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBSaveActionPerformed

        if (!check()) {
            return;
        }

        new AutoMBox(EditBillingTemplate.class.getName()) {
            @Override
            public void do_stuff() throws Exception {
                gui_to_var();
                Transaction trans = getTransaction();
                DefaultInsertOrUpdater.insertOrUpdateValuesWithPrimKey(trans, entity, entity.hist, root.getUserName());
                trans.commit();
                saved = true;
                close();
            }
        };

    }//GEN-LAST:event_jBSaveActionPerformed

    private void jBCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCloseActionPerformed

        close();
    }//GEN-LAST:event_jBCloseActionPerformed

    private boolean check() {
        if (entity.name.toString().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Bitte einen Namen eingeben.", "Fehler", JOptionPane.ERROR_MESSAGE);
            jTName.requestFocus();
            return false;
        }
        return true;
    }

    public boolean pressedSave() {
        return saved;
    }

    final public void bindVar(javax.swing.JTextField field, DBString var) {
        super.bindVar(field, var);
        field.setDocument(new DocumentFieldLimit(var.getMaxLen()));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBClose;
    private javax.swing.JButton jBDownload;
    private javax.swing.JButton jBSave;
    private javax.swing.JButton jBUpload;
    private javax.swing.JLabel jLFileName;
    private javax.swing.JLabel jLabelDescription;
    private javax.swing.JLabel jLabelFile;
    private javax.swing.JLabel jLabelName;
    private javax.swing.JPanel jPanelActions;
    private javax.swing.JPanel jPanelButtons;
    private javax.swing.JTextField jTDescription;
    private javax.swing.JTextField jTName;
    // End of variables declaration//GEN-END:variables
}
