#!/usr/bin/env bash
# Generated by AI (GitHub Copilot / Claude Sonnet 4.6)
# ---modification start---
#
# build-dist.sh
# Creates Eclipse-style app-image zip distributions for Linux x64 and Windows x64
# using jlink for the bundled JRE.
#
# Prerequisites:
#   1. Run scripts/download-jdks.sh first (downloads JDK binaries to jdks/)
#   2. Run 'mvn package -DskipTests' from the combined root first
#
# Output:
#   TwelveLittleScoutsClerk/dist/ScoutsClerk-linux-x64/   + .zip
#   TwelveLittleScoutsClerk/dist/ScoutsClerk-windows-x64/ + .zip
#
# Usage (run from the TwelveLittleScoutsClerk/ directory):
#   bash scripts/build-dist.sh             # builds both platforms
#   bash scripts/build-dist.sh --linux     # Linux only
#   bash scripts/build-dist.sh --windows   # Windows only

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
APP_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"      # TwelveLittleScoutsClerk/
TARGET_DIR="$APP_DIR/target"
DIST_DIR="$APP_DIR/dist"
JDK_DIR="$APP_DIR/jdks"

APP_NAME="ScoutsClerk"
APP_JAR="TwelveLittleScoutsClerk-1.0-SNAPSHOT.jar"

# JDK modules required for a Swing desktop app with Derby DB, JDBC, XML and logging.
# java.desktop   -> Swing / AWT
# java.sql       -> JDBC (Derby, MySQL, MariaDB)
# java.naming    -> JNDI (required by Derby)
# java.management-> JMX  (required by Derby)
# java.xml       -> XML parsing (Apache POI / Excel)
# java.prefs     -> Preferences API (framework config)
# jdk.crypto.ec  -> TLS / SSL (JDBC over SSL)
# java.net.http  -> HTTP client (MariaDB driver)
# jdk.localedata -> Full locale data (date/number formatting)
MODULES="java.base,java.desktop,java.logging,java.sql,java.naming,java.management,java.xml,java.prefs,jdk.crypto.ec,java.security.jgss,java.net.http,jdk.localedata"

# ---------------------------------------------------------------------------
# Argument parsing
# ---------------------------------------------------------------------------
BUILD_LINUX=false
BUILD_WINDOWS=false

if [[ $# -eq 0 ]]; then
    BUILD_LINUX=true
    BUILD_WINDOWS=true
fi

for arg in "$@"; do
    case "$arg" in
        --linux)   BUILD_LINUX=true ;;
        --windows) BUILD_WINDOWS=true ;;
        --all)     BUILD_LINUX=true; BUILD_WINDOWS=true ;;
        *) echo "Unknown argument: $arg" >&2; exit 1 ;;
    esac
done

# ---------------------------------------------------------------------------
# Sanity checks
# ---------------------------------------------------------------------------
if [[ ! -f "$TARGET_DIR/$APP_JAR" ]]; then
    echo "ERROR: $TARGET_DIR/$APP_JAR not found." >&2
    echo "       Run 'mvn package -Dmaven.test.skip=true' from the combined root first." >&2
    exit 1
fi

# Use the bundled Linux JDK jlink to guarantee the same major version as downloaded jmods.
# On Linux we cannot execute windows/bin/jlink, so this binary is used for both targets.
JLINK_BIN="$JDK_DIR/linux/bin/jlink"

if [[ ! -x "$JLINK_BIN" ]]; then
    echo "ERROR: $JLINK_BIN not found/executable." >&2
    echo "       Run:  bash scripts/download-jdks.sh" >&2
    exit 1
fi

if ! command -v zip &>/dev/null; then
    echo "ERROR: zip not found on PATH. Install it with: sudo apt install zip" >&2
    exit 1
fi

mkdir -p "$DIST_DIR"

# ---------------------------------------------------------------------------
# build_appimage PLATFORM JDK_PATH
#   PLATFORM : linux | windows
#   JDK_PATH : path to the extracted JDK for that platform (contains jmods/)
# ---------------------------------------------------------------------------
build_appimage() {
    local PLATFORM="$1"
    local JDK_PATH="$2"
    local OUT_NAME="${APP_NAME}-${PLATFORM}-x64"
    local OUT_DIR="$DIST_DIR/$OUT_NAME"
    local JRE_DIR="$OUT_DIR/jre"
    local ZIP_FILE="$DIST_DIR/${OUT_NAME}.zip"

    echo ""
    echo "=== Building app-image: $OUT_NAME ==="

    # Clean any previous build
    rm -rf "$OUT_DIR"
    mkdir -p "$OUT_DIR/lib"

    # --- Step 1: Copy app JAR and all runtime dependencies ---
    echo "[copy]   Copying JARs ..."
    cp "$TARGET_DIR/$APP_JAR"   "$OUT_DIR/lib/"
    cp "$TARGET_DIR/lib/"*.jar  "$OUT_DIR/lib/"

    # --- Step 2: Create minimal custom JRE via jlink ---
    echo "[jlink]  Creating custom JRE from $JDK_PATH/jmods ..."
    "$JLINK_BIN" \
        --module-path "$JDK_PATH/jmods" \
        --add-modules "$MODULES" \
        --output "$JRE_DIR" \
        --no-header-files \
        --no-man-pages \
        --compress=zip-6 \
        --strip-debug

    # --- Step 3: Create platform launcher ---
    if [[ "$PLATFORM" == "linux" ]]; then
        local LAUNCHER="$OUT_DIR/${APP_NAME}"
        cat > "$LAUNCHER" <<EOF
#!/usr/bin/env bash
DIR="\$(cd "\$(dirname "\${BASH_SOURCE[0]}")" && pwd)"
exec "\$DIR/jre/bin/java" -jar "\$DIR/lib/${APP_JAR}" "\$@"
EOF
        chmod +x "$LAUNCHER"
    else
        # Windows: use javaw.exe (no console window) with CRLF line endings
        local LAUNCHER="$OUT_DIR/${APP_NAME}.bat"
        printf '@echo off\r\n' > "$LAUNCHER"
        printf 'SET DIR=%%~dp0\r\n' >> "$LAUNCHER"
        printf 'start "" "%%DIR%%jre\\bin\\javaw.exe" -jar "%%DIR%%lib\\%s" %%*\r\n' "$APP_JAR" >> "$LAUNCHER"
    fi

    # --- Step 4: Package as zip ---
    echo "[zip]    Creating ${OUT_NAME}.zip ..."
    rm -f "$ZIP_FILE"
    (cd "$DIST_DIR" && zip -r "$ZIP_FILE" "$OUT_NAME")

    local JRE_SIZE ZIP_SIZE
    JRE_SIZE="$(du -sh "$JRE_DIR" | cut -f1)"
    ZIP_SIZE="$(du -sh "$ZIP_FILE" | cut -f1)"
    echo "[done]   JRE size: ${JRE_SIZE}  |  ZIP: ${ZIP_SIZE}"
    echo "         → $ZIP_FILE"
}

# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------
if $BUILD_LINUX; then
    if [[ ! -d "$JDK_DIR/linux/jmods" ]]; then
        echo "ERROR: Linux JDK jmods not found at $JDK_DIR/linux/jmods" >&2
        echo "       Run:  bash scripts/download-jdks.sh" >&2
        exit 1
    fi
    build_appimage "linux" "$JDK_DIR/linux"
fi

if $BUILD_WINDOWS; then
    if [[ ! -d "$JDK_DIR/windows/jmods" ]]; then
        echo "ERROR: Windows JDK jmods not found at $JDK_DIR/windows/jmods" >&2
        echo "       Run:  bash scripts/download-jdks.sh" >&2
        exit 1
    fi
    build_appimage "windows" "$JDK_DIR/windows"
fi

echo ""
echo "=== Distribution build complete ==="
ls -lh "$DIST_DIR"/*.zip 2>/dev/null || true

# ---modification end---
