#!/usr/bin/env bash
# Generated by AI (GitHub Copilot / Claude Sonnet 4.6)
# Downloads Adoptium OpenJDK 21 binaries for Linux x64 and Windows x64.
# The extracted JDKs are used by build-dist.sh to create cross-platform app-images via jlink.
#
# Output locations:
#   TwelveLittleScoutsClerk/jdks/linux/    <- Linux JDK (jmods/ and full runtime)
#   TwelveLittleScoutsClerk/jdks/windows/  <- Windows JDK (jmods/ and full runtime)
#
# Usage:  bash scripts/download-jdks.sh  (from the TwelveLittleScoutsClerk directory)

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
JDK_DIR="$SCRIPT_DIR/../jdks"
JDK_VERSION="21"

# ---modification start---
# Modified by AI (GPT-5.3-Codex / GitHub Copilot): ensure existing cached JDK major
# version matches JDK_VERSION, otherwise force a re-download.
jdk_major_from_release() {
    local release_file="$1"
    if [[ ! -f "$release_file" ]]; then
        echo ""
        return
    fi
    sed -n 's/^JAVA_VERSION="\([0-9][0-9]*\).*/\1/p' "$release_file" | head -1
}

ensure_expected_jdk_version_or_clean() {
    local dir="$1"
    local platform="$2"
    local current_major

    if [[ -d "$dir/jmods" ]]; then
        current_major="$(jdk_major_from_release "$dir/release")"
        if [[ "$current_major" != "$JDK_VERSION" ]]; then
            echo "[$platform] Existing JDK major is '$current_major' but expected '$JDK_VERSION' -> re-downloading."
            rm -rf "$dir"
        fi
    fi
}
# ---modification end---

# Adoptium Temurin REST API — resolves to the latest GA release for the given parameters
ADOPTIUM_BASE="https://api.adoptium.net/v3/binary/latest/${JDK_VERSION}/ga"

mkdir -p "$JDK_DIR"

# ---------------------------------------------------------------------------
# Linux x64
# ---------------------------------------------------------------------------
LINUX_DIR="$JDK_DIR/linux"

ensure_expected_jdk_version_or_clean "$LINUX_DIR" "linux"

if [[ -d "$LINUX_DIR/jmods" ]]; then
    echo "[linux]  Already present at $LINUX_DIR — skipping download."
else
    echo "[linux]  Downloading JDK ${JDK_VERSION} for Linux x64 ..."
    TMP_TGZ="$JDK_DIR/jdk21-linux-x64.tar.gz"
    curl -fL# "${ADOPTIUM_BASE}/linux/x64/jdk/hotspot/normal/eclipse" -o "$TMP_TGZ"
    mkdir -p "$LINUX_DIR"
    tar -xzf "$TMP_TGZ" -C "$LINUX_DIR" --strip-components=1
    rm "$TMP_TGZ"
    echo "[linux]  Extracted to $LINUX_DIR"
fi

# ---------------------------------------------------------------------------
# Windows x64
# ---------------------------------------------------------------------------
WIN_DIR="$JDK_DIR/windows"

ensure_expected_jdk_version_or_clean "$WIN_DIR" "windows"

if [[ -d "$WIN_DIR/jmods" ]]; then
    echo "[windows] Already present at $WIN_DIR — skipping download."
else
    echo "[windows] Downloading JDK ${JDK_VERSION} for Windows x64 ..."
    TMP_ZIP="$JDK_DIR/jdk21-windows-x64.zip"
    curl -fL# "${ADOPTIUM_BASE}/windows/x64/jdk/hotspot/normal/eclipse" -o "$TMP_ZIP"

    TMP_EXTRACT="$JDK_DIR/windows-extract-tmp"
    mkdir -p "$TMP_EXTRACT"
    unzip -q "$TMP_ZIP" -d "$TMP_EXTRACT"

    # The zip contains a single top-level directory (e.g. jdk-21.0.x+7)
    INNER_DIR="$(find "$TMP_EXTRACT" -maxdepth 1 -mindepth 1 -type d | head -1)"
    mv "$INNER_DIR" "$WIN_DIR"
    rm -rf "$TMP_EXTRACT" "$TMP_ZIP"
    echo "[windows] Extracted to $WIN_DIR"
fi

echo ""
echo "Done.  jmods directories:"
echo "  Linux:   $LINUX_DIR/jmods"
echo "  Windows: $WIN_DIR/jmods"
