#!/usr/bin/env bash
# Generated by AI (GitHub Copilot)
# ---modification start---
# AI modification start (GitHub Copilot / DeepSeek V4 Pro)
#
# generate-moneybag-icon.sh
# Generates SVG, PNG, and ICO icons for the ScoutsClerk application.
#
# Output:
#   scripts/scoutsclerk.svg   – vector icon for KDE launcher and desktop file
#   scripts/scoutsclerk.png   – 64x64 PNG for the Java application window icon
#   scripts/scoutsclerk.ico   – multi-size ICO for Windows distribution
#
# Prerequisites:
#   - librsvg2-bin   (rsvg-convert)  -> PNG generation
#   - imagemagick    (convert)       -> ICO generation
#
# Usage:
#   bash scripts/generate-moneybag-icon.sh

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
APP_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"

SVG_OUTPUT="$SCRIPT_DIR/scoutsclerk.svg"
PNG_OUTPUT="$SCRIPT_DIR/scoutsclerk.png"
ICO_OUTPUT="$SCRIPT_DIR/scoutsclerk.ico"

# Destination in Java resources (so the app finds it at runtime)
RESOURCES_ICONS_DIR="$APP_DIR/src/at/redeye/twelvelittlescoutsclerk/resources/icons"

cat > "$SVG_OUTPUT" << 'SVGEOF'
<?xml version="1.0" encoding="UTF-8"?>
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 64 64" width="64" height="64">
  <!-- Bag body -->
  <path d="
    M 12 28
    C 12 18, 20 10, 32 10
    C 44 10, 52 18, 52 28
    L 52 52
    C 52 56, 48 58, 44 58
    L 20 58
    C 16 58, 12 56, 12 52
    Z
  " fill="#8B6914" stroke="#5C4A0E" stroke-width="1.5" stroke-linejoin="round"/>

  <!-- Rope/drawstring -->
  <path d="
    M 16 28
    C 18 24, 24 22, 32 22
    C 40 22, 46 24, 48 28
  " fill="none" stroke="#C4A035" stroke-width="2.5" stroke-linecap="round"/>

  <!-- Dollar sign ($) -->
  <text x="32" y="46" text-anchor="middle" font-family="Arial, sans-serif"
        font-size="28" font-weight="bold" fill="#FFD700" stroke="#5C4A0E"
        stroke-width="0.8" paint-order="stroke fill">$</text>

  <!-- Bag highlight (left side) -->
  <path d="
    M 14 30
    C 14 38, 16 50, 20 56
  " fill="none" stroke="rgba(255,255,255,0.2)" stroke-width="3" stroke-linecap="round"/>

  <!-- Rope bow/knot -->
  <ellipse cx="32" cy="28" rx="4" ry="2.5" fill="#C4A035" stroke="#9B7B1E" stroke-width="0.8"/>
  <path d="M 28 28 Q 24 24, 22 26" fill="none" stroke="#C4A035" stroke-width="1.8" stroke-linecap="round"/>
  <path d="M 36 28 Q 40 24, 42 26" fill="none" stroke="#C4A035" stroke-width="1.8" stroke-linecap="round"/>
</svg>
SVGEOF

echo "Generated: $SVG_OUTPUT"

# --- Generate PNG (64x64) for Java window icon ---
if command -v rsvg-convert &>/dev/null; then
    rsvg-convert -w 64 -h 64 -o "$PNG_OUTPUT" "$SVG_OUTPUT"
    echo "Generated: $PNG_OUTPUT"
else
    echo "WARNING: rsvg-convert not found – skipping PNG generation" >&2
fi

# --- Generate ICO (multi-size) for Windows distribution ---
if command -v convert &>/dev/null; then
    # Build a multi-size ICO: 16, 32, 48, 64
    convert "$PNG_OUTPUT" \
        \( -clone 0 -resize 16x16 \) \
        \( -clone 0 -resize 32x32 \) \
        \( -clone 0 -resize 48x48 \) \
        -delete 0 \
        "$ICO_OUTPUT"
    echo "Generated: $ICO_OUTPUT"
else
    echo "WARNING: convert (ImageMagick) not found – skipping ICO generation" >&2
fi

# --- Copy PNG to Java resources so Main.java can load it ---
if [[ -f "$PNG_OUTPUT" ]]; then
    mkdir -p "$RESOURCES_ICONS_DIR"
    cp "$PNG_OUTPUT" "$RESOURCES_ICONS_DIR/logo.png"
    echo "Copied PNG to: $RESOURCES_ICONS_DIR/logo.png"
else
    echo "WARNING: PNG not available, cannot copy to resources" >&2
fi
# AI modification end
# ---modification end---
