#!/usr/bin/env bash
# Generated by AI (GitHub Copilot)
# ---modification start---
#
# install-desktop-kde.sh
# Installs the ScoutsClerk launcher locally for KDE Plasma desktop.
#
# What this does:
#   1. Creates ~/.local/share/applications/scoutsclerk.desktop
#   2. Creates ~/.local/share/icons/hicolor/scalable/apps/scoutsclerk.svg
#   3. Copies the application jar and lib/ to /opt/scoutsclerk/ (requires sudo)
#   4. Runs kbuildsycoca5 to refresh the KDE application menu
#
# If you prefer a user-only install (no sudo), set SYSTEM_INSTALL=false and
# adjust APP_INSTALL_DIR below.
#
# Usage (run from the TwelveLittleScoutsClerk/ directory):
#   bash scripts/install-desktop-kde.sh
#   bash scripts/install-desktop-kde.sh --user-only   # no sudo, installs jar to ~/.local/share/scoutsclerk/

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
APP_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
TARGET_DIR="$APP_DIR/target"
APP_JAR="TwelveLittleScoutsClerk-1.0-SNAPSHOT.jar"
APP_NAME="ScoutsClerk"

# --- configuration ---
SYSTEM_INSTALL=true
APP_INSTALL_DIR="/opt/scoutsclerk"
DESKTOP_FILE_SRC="$SCRIPT_DIR/scoutsclerk.desktop"
ICON_SRC="$SCRIPT_DIR/scoutsclerk.svg"

# --- argument parsing ---
while [[ $# -gt 0 ]]; do
    case "$1" in
        --user-only)
            SYSTEM_INSTALL=false
            APP_INSTALL_DIR="$HOME/.local/share/scoutsclerk"
            shift
            ;;
        --help|-h)
            echo "Usage: $0 [--user-only]"
            echo "  --user-only   Install entirely in user home (no sudo required)"
            exit 0
            ;;
        *)
            echo "Unknown option: $1"
            exit 1
            ;;
    esac
done

# --- validate ---
JAR_PATH="$TARGET_DIR/$APP_JAR"
if [[ ! -f "$JAR_PATH" ]]; then
    echo "ERROR: Application jar not found at $JAR_PATH"
    echo "       Run 'mvn package -DskipTests' first."
    exit 1
fi

if [[ ! -f "$DESKTOP_FILE_SRC" ]]; then
    echo "ERROR: .desktop file not found at $DESKTOP_FILE_SRC"
    exit 1
fi

# --- generate icon if missing ---
if [[ ! -f "$ICON_SRC" ]]; then
    echo "Icon not found, generating money bag SVG..."
    bash "$SCRIPT_DIR/generate-moneybag-icon.sh"
fi

echo "=== Installing ScoutsClerk ==="
echo "Install dir: $APP_INSTALL_DIR"

# --- 1. Copy application files ---
if [[ "$SYSTEM_INSTALL" == true ]]; then
    echo "--- Installing application to $APP_INSTALL_DIR (requires sudo) ---"
    sudo mkdir -p "$APP_INSTALL_DIR"
    sudo cp "$JAR_PATH" "$APP_INSTALL_DIR/"
    if [[ -d "$TARGET_DIR/lib" ]]; then
        sudo rm -rf "$APP_INSTALL_DIR/lib" 2>/dev/null || true
        sudo cp -r "$TARGET_DIR/lib" "$APP_INSTALL_DIR/"
    fi
else
    echo "--- Installing application to $APP_INSTALL_DIR ---"
    mkdir -p "$APP_INSTALL_DIR"
    cp "$JAR_PATH" "$APP_INSTALL_DIR/"
    if [[ -d "$TARGET_DIR/lib" ]]; then
        rm -rf "$APP_INSTALL_DIR/lib" 2>/dev/null || true
        cp -r "$TARGET_DIR/lib" "$APP_INSTALL_DIR/"
    fi
fi

# --- 2. Install desktop file ---
DESKTOP_DEST="$HOME/.local/share/applications/scoutsclerk.desktop"
echo "--- Installing .desktop file to $DESKTOP_DEST ---"
mkdir -p "$(dirname "$DESKTOP_DEST")"

# Generate .desktop with correct paths
cat > "$DESKTOP_DEST" << DESKTOPEOF
[Desktop Entry]
Type=Application
Name=ScoutsClerk
GenericName=12 Little Scouts Clerk
Comment=Scouts financial management application
Exec=java -jar $APP_INSTALL_DIR/$APP_JAR
Path=$APP_INSTALL_DIR
Icon=scoutsclerk
Terminal=false
Categories=Office;Finance;
StartupNotify=true
DESKTOPEOF

# --- 3. Install icon ---
ICON_DEST="$HOME/.local/share/icons/hicolor/scalable/apps/scoutsclerk.svg"
echo "--- Installing icon to $ICON_DEST ---"
mkdir -p "$(dirname "$ICON_DEST")"
cp "$ICON_SRC" "$ICON_DEST"

# --- 4. Refresh KDE menu ---
echo "--- Refreshing KDE application menu ---"
if command -v kbuildsycoca5 &>/dev/null; then
    kbuildsycoca5 --noincremental 2>/dev/null || true
elif command -v kbuildsycoca6 &>/dev/null; then
    kbuildsycoca6 --noincremental 2>/dev/null || true
else
    echo "WARNING: kbuildsycoca not found. Application may not appear in menu."
    echo "         Log out and back in to refresh the application menu."
fi

echo ""
echo "=== Installation complete ==="
echo "You should now find 'ScoutsClerk' in your application menu under Office/Finance."
echo "To launch from terminal: java -jar $APP_INSTALL_DIR/$APP_JAR"
# ---modification end---
