/**
 * TwelveLittleScoutsClerk EPC QR code generation helper
 * @author Copyright (c) 2023-2026 Martin Oberzalek
 */
package at.redeye.twelvelittlescoutsclerk;

import com.google.zxing.BarcodeFormat;
import com.google.zxing.EncodeHintType;
import com.google.zxing.WriterException;
import com.google.zxing.client.j2se.MatrixToImageWriter;
import com.google.zxing.common.BitMatrix;
import com.google.zxing.qrcode.QRCodeWriter;
import com.google.zxing.qrcode.decoder.ErrorCorrectionLevel;
import java.awt.image.BufferedImage;
import java.util.EnumMap;
import java.util.Map;

// generated by AI (Claude Sonnet 4.6)
public class EpcQrHelper {

    private static final String VERSION = "002";
    private static final String CHARACTER_SET = "1"; // UTF-8
    private static final String IDENTIFICATION = "SCT";
    private static final String CURRENCY = "EUR";

    /**
     * Builds the EPC QR code payload string (newline-delimited).
     *
     * @param beneficiaryName          Name of the payee (max 70 chars)
     * @param iban                     IBAN of the payee — spaces are stripped automatically
     * @param bic                      BIC of the payee's bank; pass empty string for v002 (optional)
     * @param amountEur                Amount in EUR; 0.0 means "unspecified"
     * @param remittanceUnstructured   Free-text payment reference (max 140 chars); pass empty string if unused
     * @param purposeCode              4-char ISO 20022 purpose code (e.g. "CHAR"); pass empty string to omit
     * @return the EPC payload string, ready to be encoded into a QR code
     */
    // generated by AI (Claude Sonnet 4.6)
    public static String buildEpcPayload(String beneficiaryName, String iban,
            String bic, double amountEur, String remittanceUnstructured,
            String purposeCode) {

        if (beneficiaryName == null || beneficiaryName.isEmpty()) {
            throw new IllegalArgumentException("Beneficiary name is required");
        }
        if (beneficiaryName.length() > 70) {
            throw new IllegalArgumentException("Beneficiary name must be <= 70 characters");
        }
        if (iban == null || iban.isEmpty()) {
            throw new IllegalArgumentException("IBAN is required");
        }

        // Strip spaces from IBAN
        String cleanIban = iban.replaceAll("\\s+", "");

        // Format amount: EUR0 means unspecified; otherwise EUR<decimal>
        String amountStr;
        if (amountEur <= 0.0) {
            amountStr = "";
        } else {
            amountStr = String.format("%s%.2f", CURRENCY, amountEur);
        }

        String safeBic = (bic == null) ? "" : bic.trim();
        String safePurpose = (purposeCode == null) ? "" : purposeCode.trim();
        String safeRemittance = (remittanceUnstructured == null) ? "" : remittanceUnstructured.trim();
        if (safeRemittance.length() > 140) {
            safeRemittance = safeRemittance.substring(0, 140);
        }

        // EPC payload: 12 lines, LF-separated
        // Line 10 (structured reference) is left blank; line 11 is unstructured remittance
        return "BCD\n"
                + VERSION + "\n"
                + CHARACTER_SET + "\n"
                + IDENTIFICATION + "\n"
                + safeBic + "\n"
                + beneficiaryName + "\n"
                + cleanIban + "\n"
                + amountStr + "\n"
                + safePurpose + "\n"
                + "\n"                    // structured reference — leave blank
                + safeRemittance + "\n"
                + "";                     // beneficiary-to-originator info — omitted
    }

    /**
     * Encodes an EPC payload string as a QR code image.
     *
     * @param epcPayload  the string returned by {@link #buildEpcPayload}
     * @param sizePixels  width and height of the resulting square image in pixels (e.g. 200)
     * @return a {@link BufferedImage} containing the QR code
     * @throws WriterException if ZXing fails to encode the payload
     */
    // generated by AI (Claude Sonnet 4.6)
    public static BufferedImage generateQrImage(String epcPayload, int sizePixels)
            throws WriterException {

        Map<EncodeHintType, Object> hints = new EnumMap<>(EncodeHintType.class);
        hints.put(EncodeHintType.ERROR_CORRECTION, ErrorCorrectionLevel.M); // EPC spec requires M
        hints.put(EncodeHintType.CHARACTER_SET, "UTF-8");
        hints.put(EncodeHintType.MARGIN, 1); // quiet zone in modules

        QRCodeWriter writer = new QRCodeWriter();
        BitMatrix matrix = writer.encode(epcPayload, BarcodeFormat.QR_CODE, sizePixels, sizePixels, hints);
        return MatrixToImageWriter.toBufferedImage(matrix);
    }

    /**
     * Convenience method: generates an EPC QR code using the organisation's
     * IBAN and name from {@link AppConfigDefinitions}.
     *
     * No BIC is included (EPC v002, recommended for SEPA-only).
     *
     * @param amountEur   amount in EUR; pass 0.0 to leave amount unspecified
     * @param remittance  free-text payment reference shown to the payer (max 140 chars)
     * @return a 300×300 pixel QR code image
     * @throws WriterException if ZXing fails to encode
     */
    // generated by AI (Claude Sonnet 4.6)
    public static BufferedImage generateBillQr(double amountEur, String remittance)
            throws WriterException {

        String name = AppConfigDefinitions.Organisation.getConfigValue();
        String iban = AppConfigDefinitions.OrganisaiontIBAN.getConfigValue();

        String payload = buildEpcPayload(name, iban, "", amountEur, remittance, "");
        return generateQrImage(payload, 300);
    }
}
